In [56]:
# TensorFlow and tf.keras
import tensorflow as tf
from tensorflow import keras

# Helper libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


print(tf.__version__)

2.1.0


In [62]:
df = pd.read_csv('full_results.csv', index_col='dataid')
df_features = df[['ARIMA', 'Holt-Winters', 'TESLA', 'LSTM-20-7']]
df_labels = df[['Actual']]

df_features['ARIMA'] = df_features['ARIMA'].apply(eval)
df_features['Holt-Winters'] = df_features['Holt-Winters'].apply(eval)
df_features['TESLA'] = df_features['TESLA'].apply(eval)
df_features['LSTM-20-7'] = df_features['LSTM-20-7'].apply(eval)

df_labels['Actual'] = df_labels['Actual'].apply(eval)

total_features = df_features.values.tolist()
total_labels = df_labels.values.tolist()

for x in range(len(total_labels)) :
    while len(total_labels[x][0]) < 7027 :
        total_labels[x][0].append(0)
        
for x in range(len(total_features)) :
    for y in range(len(total_features[x])) :
        while len(total_features[x][y]) < 7027 :
            total_features[x][y].append(0)

new_total_features = np.array(total_features, order=2)
new_total_labels = np.array(total_labels, order=3)


train_houses = new_total_features[:18]
test_houses = new_total_features[18:]
train_labels = new_total_labels[:18]
test_labels = new_total_labels[18:]


df_training = pd.read_csv('trainingMeanData.csv', index_col='dataid')

training_list = df_training.values
training_list.shape

gate_training = training_list[:18]
gate_testing = training_list[18:]

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  
/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/s

In [63]:
model = keras.Sequential([
    keras.layers.Dense(17, input_shape=(17,), activation='softmax'),
#     keras.layers.Dense(20, activation='softmax'),
#     keras.layers.Dense(20, activation='softmax'),
    keras.layers.Dense(100, activation='softmax'),
    keras.layers.Dense(100, activation='softmax'),
    keras.layers.Dense(200, activation='softmax'),
    keras.layers.Dense(100, activation='softmax'),
    keras.layers.Dense(100, activation='softmax'),
    keras.layers.Dense(4, activation='softmax')
])

In [64]:
from sklearn.metrics import mean_squared_error
import keras.backend as K

def test_loss(features, train) :
    
    def custom_loss(y_actual, y_predicted) :
        total = 0
        tf.print(y_predicted[0])
        for x in range(features.shape[0]) :    
            
            new_arima = curr_total_features[x][0] * y_predicted[0][0]
            new_holt = curr_total_features[x][1] * y_predicted[0][1]
            new_tesla = curr_total_features[x][2] * y_predicted[0][2]
            new_lstm = curr_total_features[x][3] * y_predicted[0][3]
    
            new = tf.math.add(new_arima, new_holt)
            new = tf.math.add(new, new_tesla)
            new = tf.math.add(new, new_lstm)
            
            total = total + K.mean(K.square(new - train[x]))


        return total / features.shape[0]
    
    return custom_loss

curr_total_features = tf.Variable(train_houses, dtype=tf.float32)
labels = train_labels
model.compile(optimizer='adam',
              loss=test_loss(curr_total_features, labels))

In [65]:
model.fit(gate_training, train_labels, epochs=5000)

Train on 18 samples
Epoch 1/5000
[0.249622285 0.248290613 0.247552872 0.254534215]
18/18 [==============================] - 3s 139ms/sample - loss: 0.0857
Epoch 2/5000
[0.249112189 0.247773722 0.248055443 0.255058736]
18/18 [==============================] - 0s 560us/sample - loss: 0.0855
Epoch 3/5000
[0.248600483 0.247254699 0.248559579 0.255585253]
18/18 [==============================] - 0s 456us/sample - loss: 0.0852
Epoch 4/5000
[0.248087972 0.246734589 0.249064535 0.256112874]
18/18 [==============================] - 0s 416us/sample - loss: 0.0850
Epoch 5/5000
[0.247574955 0.246213809 0.24957 0.256641239]
18/18 [==============================] - 0s 374us/sample - loss: 0.0848
Epoch 6/5000
[0.247061595 0.245692521 0.250075758 0.257170111]
18/18 [==============================] - 0s 3ms/sample - loss: 0.0845
Epoch 7/5000
[0.246548012 0.245170876 0.250581712 0.25769937]
18/18 [==============================] - 0s 428us/sample - loss: 0.0843
Epoch 8/5000
[0.246034279 0.244649 0.25108

Epoch 62/5000
[0.218808919 0.217010945 0.27777949 0.286400676]
18/18 [==============================] - 0s 398us/sample - loss: 0.0725
Epoch 63/5000
[0.218321592 0.216517553 0.278254092 0.286906779]
18/18 [==============================] - 0s 387us/sample - loss: 0.0723
Epoch 64/5000
[0.217835024 0.21602504 0.27872777 0.287412137]
18/18 [==============================] - 0s 387us/sample - loss: 0.0721
Epoch 65/5000
[0.217349246 0.215533361 0.279200613 0.287916809]
18/18 [==============================] - 0s 365us/sample - loss: 0.0719
Epoch 66/5000
[0.216864273 0.215042561 0.279672503 0.288420707]
18/18 [==============================] - 0s 380us/sample - loss: 0.0717
Epoch 67/5000
[0.216380075 0.214552581 0.280143529 0.28892386]
18/18 [==============================] - 0s 1ms/sample - loss: 0.0715
Epoch 68/5000
[0.215896681 0.21406348 0.280613601 0.289426267]
18/18 [==============================] - 0s 354us/sample - loss: 0.0713
Epoch 69/5000
[0.215414077 0.213575229 0.281082779 0.28

18/18 [==============================] - 0s 354us/sample - loss: 0.0619
Epoch 123/5000
[0.190648049 0.188604951 0.304952443 0.315794528]
18/18 [==============================] - 0s 383us/sample - loss: 0.0618
Epoch 124/5000
[0.190214843 0.188169733 0.30536595 0.31624952]
18/18 [==============================] - 0s 374us/sample - loss: 0.0616
Epoch 125/5000
[0.18978256 0.187735528 0.305778384 0.316703558]
18/18 [==============================] - 0s 488us/sample - loss: 0.0615
Epoch 126/5000
[0.189351246 0.187302351 0.306189716 0.317156702]
18/18 [==============================] - 0s 377us/sample - loss: 0.0613
Epoch 127/5000
[0.188920885 0.186870188 0.3066 0.317608923]
18/18 [==============================] - 0s 364us/sample - loss: 0.0612
Epoch 128/5000
[0.188491508 0.186439067 0.30700922 0.318060279]
18/18 [==============================] - 0s 1ms/sample - loss: 0.0610
Epoch 129/5000
[0.18806307 0.186008945 0.307417274 0.318510681]
18/18 [==============================] - 0s 389us/sam

Epoch 183/5000
[0.166375905 0.164308071 0.327840775 0.341475278]
18/18 [==============================] - 0s 378us/sample - loss: 0.0536
Epoch 184/5000
[0.166001081 0.163934246 0.328189045 0.341875583]
18/18 [==============================] - 0s 382us/sample - loss: 0.0535
Epoch 185/5000
[0.165627226 0.163561419 0.328536302 0.342275053]
18/18 [==============================] - 0s 368us/sample - loss: 0.0533
Epoch 186/5000
[0.165254369 0.163189605 0.328882456 0.3426736]
18/18 [==============================] - 0s 391us/sample - loss: 0.0532
Epoch 187/5000
[0.164882451 0.162818789 0.329227537 0.343071282]
18/18 [==============================] - 0s 379us/sample - loss: 0.0531
Epoch 188/5000
[0.164511487 0.162448943 0.329571515 0.34346804]
18/18 [==============================] - 0s 374us/sample - loss: 0.0530
Epoch 189/5000
[0.164141491 0.162080124 0.32991448 0.343863964]
18/18 [==============================] - 0s 1ms/sample - loss: 0.0529
Epoch 190/5000
[0.163772434 0.161712274 0.33025

18/18 [==============================] - 0s 348us/sample - loss: 0.0473
Epoch 244/5000
[0.145235628 0.143283367 0.34715423 0.364326745]
18/18 [==============================] - 0s 381us/sample - loss: 0.0472
Epoch 245/5000
[0.144917309 0.142967701 0.347438961 0.364676]
18/18 [==============================] - 0s 348us/sample - loss: 0.0471
Epoch 246/5000
[0.144599885 0.142652899 0.347722709 0.365024507]
18/18 [==============================] - 0s 356us/sample - loss: 0.0470
Epoch 247/5000
[0.144283339 0.142339 0.348005474 0.365372241]
18/18 [==============================] - 0s 352us/sample - loss: 0.0469
Epoch 248/5000
[0.143967643 0.142025992 0.348287225 0.365719199]
18/18 [==============================] - 0s 355us/sample - loss: 0.0468
Epoch 249/5000
[0.143652827 0.141713858 0.348567963 0.366065353]
18/18 [==============================] - 0s 346us/sample - loss: 0.0467
Epoch 250/5000
[0.143338859 0.141402617 0.348847747 0.366410762]
18/18 [==============================] - 0s 354u

Epoch 304/5000
[0.127617866 0.125844643 0.362539023 0.383998483]
18/18 [==============================] - 0s 358us/sample - loss: 0.0424
Epoch 305/5000
[0.127348498 0.125578508 0.362767309 0.384305716]
18/18 [==============================] - 0s 355us/sample - loss: 0.0423
Epoch 306/5000
[0.127079874 0.125313103 0.362994701 0.384612292]
18/18 [==============================] - 0s 1ms/sample - loss: 0.0423
Epoch 307/5000
[0.126812011 0.125048444 0.363221228 0.384918302]
18/18 [==============================] - 0s 369us/sample - loss: 0.0422
Epoch 308/5000
[0.126544863 0.124784559 0.363446891 0.385223657]
18/18 [==============================] - 0s 366us/sample - loss: 0.0421
Epoch 309/5000
[0.12627849 0.124521412 0.36367166 0.385528415]
18/18 [==============================] - 0s 360us/sample - loss: 0.0421
Epoch 310/5000
[0.126012862 0.124259025 0.363895595 0.385832578]
18/18 [==============================] - 0s 346us/sample - loss: 0.0420
Epoch 311/5000
[0.125747934 0.123997375 0.364

18/18 [==============================] - 0s 365us/sample - loss: 0.0387
Epoch 365/5000
[0.112486176 0.110912248 0.374922305 0.401679277]
18/18 [==============================] - 0s 367us/sample - loss: 0.0387
Epoch 366/5000
[0.112258829 0.11068815 0.375100404 0.401952624]
18/18 [==============================] - 0s 358us/sample - loss: 0.0386
Epoch 367/5000
[0.112032138 0.110464677 0.375277698 0.402225435]
18/18 [==============================] - 0s 345us/sample - loss: 0.0386
Epoch 368/5000
[0.111806065 0.110241845 0.375454277 0.402497798]
18/18 [==============================] - 0s 356us/sample - loss: 0.0385
Epoch 369/5000
[0.111580588 0.110019624 0.375630111 0.402769685]
18/18 [==============================] - 0s 1ms/sample - loss: 0.0385
Epoch 370/5000
[0.111355744 0.109798029 0.375805169 0.403041065]
18/18 [==============================] - 0s 404us/sample - loss: 0.0384
Epoch 371/5000
[0.111131534 0.109577045 0.375979483 0.403312]
18/18 [==============================] - 0s 352

Epoch 425/5000
[0.0998901725 0.0985062644 0.384319395 0.41728422]
18/18 [==============================] - 0s 340us/sample - loss: 0.0359
Epoch 426/5000
[0.0996971279 0.098316282 0.384454787 0.417531788]
18/18 [==============================] - 0s 359us/sample - loss: 0.0358
Epoch 427/5000
[0.09950459 0.0981268212 0.384589612 0.417778909]
18/18 [==============================] - 0s 371us/sample - loss: 0.0358
Epoch 428/5000
[0.0993125886 0.0979379 0.384723812 0.418025762]
18/18 [==============================] - 0s 383us/sample - loss: 0.0357
Epoch 429/5000
[0.0991210788 0.0977494642 0.384857267 0.418272197]
18/18 [==============================] - 0s 353us/sample - loss: 0.0357
Epoch 430/5000
[0.0989300758 0.0975615308 0.384990126 0.418518275]
18/18 [==============================] - 0s 359us/sample - loss: 0.0356
Epoch 431/5000
[0.0987396 0.0973741114 0.385122269 0.418763965]
18/18 [==============================] - 0s 349us/sample - loss: 0.0356
Epoch 432/5000
[0.0985496342 0.097187

18/18 [==============================] - 0s 358us/sample - loss: 0.0337
Epoch 485/5000
[0.0891695321 0.0879646838 0.39133203 0.431533754]
18/18 [==============================] - 0s 351us/sample - loss: 0.0336
Epoch 486/5000
[0.0890047774 0.0878028497 0.391430557 0.431761771]
18/18 [==============================] - 0s 348us/sample - loss: 0.0336
Epoch 487/5000
[0.0888404846 0.0876414254 0.391528547 0.431989551]
18/18 [==============================] - 0s 346us/sample - loss: 0.0336
Epoch 488/5000
[0.0886765942 0.0874804184 0.391625911 0.432217032]
18/18 [==============================] - 0s 355us/sample - loss: 0.0335
Epoch 489/5000
[0.0885131359 0.0873198509 0.391722739 0.432444245]
18/18 [==============================] - 0s 345us/sample - loss: 0.0335
Epoch 490/5000
[0.0883500949 0.0871596783 0.391819 0.432671219]
18/18 [==============================] - 0s 351us/sample - loss: 0.0335
Epoch 491/5000
[0.0881874934 0.0869999602 0.391914666 0.432897896]
18/18 [========================

Epoch 544/5000
[0.0801399201 0.0790999 0.396204144 0.444556087]
18/18 [==============================] - 0s 1ms/sample - loss: 0.0319
Epoch 545/5000
[0.0799982399 0.0789609 0.396270871 0.44477]
18/18 [==============================] - 0s 354us/sample - loss: 0.0319
Epoch 546/5000
[0.0798569322 0.0788222626 0.396337152 0.444983631]
18/18 [==============================] - 0s 364us/sample - loss: 0.0318
Epoch 547/5000
[0.0797159672 0.078684 0.396402895 0.445197105]
18/18 [==============================] - 0s 348us/sample - loss: 0.0318
Epoch 548/5000
[0.0795753747 0.0785460547 0.396468163 0.44541043]
18/18 [==============================] - 0s 383us/sample - loss: 0.0318
Epoch 549/5000
[0.0794351101 0.0784084722 0.396532863 0.445623517]
18/18 [==============================] - 0s 395us/sample - loss: 0.0318
Epoch 550/5000
[0.0792952254 0.0782712325 0.396597207 0.445836395]
18/18 [==============================] - 0s 351us/sample - loss: 0.0317
Epoch 551/5000
[0.0791556388 0.0781343579 0.

Epoch 604/5000
[0.0722329915 0.0713469833 0.399352431 0.457067639]
18/18 [==============================] - 0s 365us/sample - loss: 0.0305
Epoch 605/5000
[0.0721108094 0.071227245 0.399390727 0.457271129]
18/18 [==============================] - 0s 352us/sample - loss: 0.0304
Epoch 606/5000
[0.0719889328 0.0711078197 0.399428546 0.457474619]
18/18 [==============================] - 0s 334us/sample - loss: 0.0304
Epoch 607/5000
[0.0718673542 0.0709886774 0.399465978 0.457678]
18/18 [==============================] - 0s 362us/sample - loss: 0.0304
Epoch 608/5000
[0.0717460811 0.0708698183 0.399502963 0.457881153]
18/18 [==============================] - 0s 350us/sample - loss: 0.0304
Epoch 609/5000
[0.0716251 0.0707512572 0.399539471 0.458084196]
18/18 [==============================] - 0s 1ms/sample - loss: 0.0304
Epoch 610/5000
[0.0715044066 0.0706329793 0.399575561 0.45828709]
18/18 [==============================] - 0s 371us/sample - loss: 0.0303
Epoch 611/5000
[0.0713839754 0.070514

18/18 [==============================] - 0s 341us/sample - loss: 0.0293
Epoch 664/5000
[0.065396741 0.0646492541 0.400892675 0.469061315]
18/18 [==============================] - 0s 340us/sample - loss: 0.0293
Epoch 665/5000
[0.065290831 0.0645455 0.400905818 0.469257832]
18/18 [==============================] - 0s 1ms/sample - loss: 0.0293
Epoch 666/5000
[0.0651851445 0.0644419938 0.400918603 0.469454288]
18/18 [==============================] - 0s 341us/sample - loss: 0.0293
Epoch 667/5000
[0.0650797039 0.0643387139 0.400930911 0.469650656]
18/18 [==============================] - 0s 343us/sample - loss: 0.0293
Epoch 668/5000
[0.0649745241 0.0642356947 0.400942862 0.469846904]
18/18 [==============================] - 0s 341us/sample - loss: 0.0292
Epoch 669/5000
[0.0648695678 0.0641328841 0.400954455 0.470043093]
18/18 [==============================] - 0s 344us/sample - loss: 0.0292
Epoch 670/5000
[0.0647648647 0.0640303493 0.400965571 0.470239192]
18/18 [===========================

Epoch 723/5000
[0.0595460162 0.0589192063 0.401018709 0.480516106]
18/18 [==============================] - 0s 359us/sample - loss: 0.0284
Epoch 724/5000
[0.0594534576 0.0588285774 0.401009917 0.480708092]
18/18 [==============================] - 0s 334us/sample - loss: 0.0284
Epoch 725/5000
[0.059361089 0.0587381199 0.401000708 0.480900049]
18/18 [==============================] - 0s 362us/sample - loss: 0.0283
Epoch 726/5000
[0.0592689626 0.0586478934 0.400991231 0.481091946]
18/18 [==============================] - 0s 345us/sample - loss: 0.0283
Epoch 727/5000
[0.0591769889 0.0585578419 0.400981337 0.481283724]
18/18 [==============================] - 0s 352us/sample - loss: 0.0283
Epoch 728/5000
[0.0590852425 0.058468 0.400971204 0.481475621]
18/18 [==============================] - 0s 348us/sample - loss: 0.0283
Epoch 729/5000
[0.0589937121 0.0583783574 0.400960654 0.48166731]
18/18 [==============================] - 0s 345us/sample - loss: 0.0283
Epoch 730/5000
[0.0589023866 0.05

18/18 [==============================] - 0s 331us/sample - loss: 0.0276
Epoch 783/5000
[0.0543386787 0.0538197309 0.399894297 0.491947383]
18/18 [==============================] - 0s 347us/sample - loss: 0.0276
Epoch 784/5000
[0.0542575382 0.0537402555 0.399865657 0.492136538]
18/18 [==============================] - 0s 2ms/sample - loss: 0.0276
Epoch 785/5000
[0.0541765504 0.0536609441 0.399836749 0.492325783]
18/18 [==============================] - 0s 362us/sample - loss: 0.0275
Epoch 786/5000
[0.0540957674 0.0535818115 0.399807483 0.492514938]
18/18 [==============================] - 0s 377us/sample - loss: 0.0275
Epoch 787/5000
[0.0540151261 0.0535028651 0.399777979 0.492704]
18/18 [==============================] - 0s 338us/sample - loss: 0.0275
Epoch 788/5000
[0.0539346598 0.0534240678 0.399748117 0.492893159]
18/18 [==============================] - 0s 355us/sample - loss: 0.0275
Epoch 789/5000
[0.0538543835 0.0533454195 0.399717957 0.493082255]
18/18 [=========================

Epoch 842/5000
[0.0498332381 0.0494069308 0.397695333 0.503064513]
18/18 [==============================] - 0s 410us/sample - loss: 0.0269
Epoch 843/5000
[0.0497615524 0.0493367203 0.397649497 0.503252268]
18/18 [==============================] - 0s 374us/sample - loss: 0.0269
Epoch 844/5000
[0.0496900193 0.0492666438 0.397603333 0.50344]
18/18 [==============================] - 0s 365us/sample - loss: 0.0269
Epoch 845/5000
[0.0496186391 0.0491967052 0.397556931 0.503627717]
18/18 [==============================] - 0s 2ms/sample - loss: 0.0269
Epoch 846/5000
[0.0495474041 0.0491269417 0.39751026 0.503815413]
18/18 [==============================] - 0s 348us/sample - loss: 0.0269
Epoch 847/5000
[0.0494763181 0.04905729 0.397463232 0.504003108]
18/18 [==============================] - 0s 360us/sample - loss: 0.0269
Epoch 848/5000
[0.0494053736 0.0489878021 0.397415936 0.504190803]
18/18 [==============================] - 0s 348us/sample - loss: 0.0269
Epoch 849/5000
[0.0493345745 0.04891

18/18 [==============================] - 0s 362us/sample - loss: 0.0264
Epoch 902/5000
[0.0457806922 0.0454361439 0.394475937 0.514307141]
18/18 [==============================] - 0s 359us/sample - loss: 0.0263
Epoch 903/5000
[0.0457172133 0.0453739204 0.394414693 0.514494181]
18/18 [==============================] - 0s 338us/sample - loss: 0.0263
Epoch 904/5000
[0.0456538349 0.0453118086 0.394353062 0.514681339]
18/18 [==============================] - 0s 352us/sample - loss: 0.0263
Epoch 905/5000
[0.0455905832 0.0452498086 0.394291282 0.514868379]
18/18 [==============================] - 0s 354us/sample - loss: 0.0263
Epoch 906/5000
[0.0455274731 0.0451879539 0.394229084 0.515055418]
18/18 [==============================] - 0s 338us/sample - loss: 0.0263
Epoch 907/5000
[0.0454644784 0.0451262072 0.394166797 0.515242457]
18/18 [==============================] - 0s 2ms/sample - loss: 0.0263
Epoch 908/5000
[0.0454016067 0.0450645871 0.394104213 0.515429556]
18/18 [======================

Epoch 961/5000
[0.0422390103 0.0419634692 0.390460789 0.525336683]
18/18 [==============================] - 0s 373us/sample - loss: 0.0259
Epoch 962/5000
[0.0421823934 0.041907914 0.390386164 0.525523484]
18/18 [==============================] - 0s 357us/sample - loss: 0.0259
Epoch 963/5000
[0.042125877 0.0418524705 0.390311301 0.525710344]
18/18 [==============================] - 0s 353us/sample - loss: 0.0259
Epoch 964/5000
[0.0420694724 0.041797135 0.390236199 0.525897264]
18/18 [==============================] - 0s 356us/sample - loss: 0.0258
Epoch 965/5000
[0.0420131609 0.0417418927 0.390160918 0.526084]
18/18 [==============================] - 0s 361us/sample - loss: 0.0258
Epoch 966/5000
[0.0419569649 0.0416867584 0.39008534 0.526270926]
18/18 [==============================] - 0s 362us/sample - loss: 0.0258
Epoch 967/5000
[0.0419008955 0.0416317545 0.390009701 0.526457667]
18/18 [==============================] - 0s 337us/sample - loss: 0.0258
Epoch 968/5000
[0.0418448932 0.041

18/18 [==============================] - 0s 340us/sample - loss: 0.0255
Epoch 1021/5000
[0.0390229 0.0388065763 0.385627061 0.536543548]
18/18 [==============================] - 0s 347us/sample - loss: 0.0254
Epoch 1022/5000
[0.038972266 0.0387568362 0.385540664 0.53673023]
18/18 [==============================] - 0s 341us/sample - loss: 0.0254
Epoch 1023/5000
[0.0389217399 0.0387071967 0.385454118 0.536917]
18/18 [==============================] - 0s 347us/sample - loss: 0.0254
Epoch 1024/5000
[0.038871292 0.0386576429 0.385367423 0.537103653]
18/18 [==============================] - 0s 1ms/sample - loss: 0.0254
Epoch 1025/5000
[0.0388209261 0.0386081673 0.38528049 0.537290335]
18/18 [==============================] - 0s 393us/sample - loss: 0.0254
Epoch 1026/5000
[0.0387706608 0.0385587849 0.385193467 0.537477136]
18/18 [==============================] - 0s 358us/sample - loss: 0.0254
Epoch 1027/5000
[0.0387204848 0.0385094956 0.385106236 0.537663817]
18/18 [=========================

18/18 [==============================] - 0s 332us/sample - loss: 0.0251
Epoch 1080/5000
[0.036186181 0.0360178798 0.380240917 0.547555]
18/18 [==============================] - 0s 325us/sample - loss: 0.0251
Epoch 1081/5000
[0.0361406133 0.035973046 0.380144894 0.547741473]
18/18 [==============================] - 0s 355us/sample - loss: 0.0251
Epoch 1082/5000
[0.0360951312 0.0359282941 0.380048543 0.547928035]
18/18 [==============================] - 0s 350us/sample - loss: 0.0251
Epoch 1083/5000
[0.0360497311 0.0358836092 0.379952133 0.548114598]
18/18 [==============================] - 0s 357us/sample - loss: 0.0251
Epoch 1084/5000
[0.0360043943 0.0358389951 0.379855543 0.548301041]
18/18 [==============================] - 0s 405us/sample - loss: 0.0251
Epoch 1085/5000
[0.0359591506 0.0357944742 0.379758865 0.548487544]
18/18 [==============================] - 0s 355us/sample - loss: 0.0251
Epoch 1086/5000
[0.0359139778 0.0357500128 0.379661947 0.548674047]
18/18 [==================

Epoch 1139/5000
[0.0336275734 0.033497788 0.37432608 0.55854851]
18/18 [==============================] - 0s 341us/sample - loss: 0.0248
Epoch 1140/5000
[0.0335863829 0.0334571749 0.374221861 0.558734536]
18/18 [==============================] - 0s 339us/sample - loss: 0.0248
Epoch 1141/5000
[0.0335452445 0.0334166177 0.374117404 0.558920741]
18/18 [==============================] - 0s 335us/sample - loss: 0.0248
Epoch 1142/5000
[0.0335041769 0.0333761089 0.374012947 0.559106767]
18/18 [==============================] - 0s 347us/sample - loss: 0.0248
Epoch 1143/5000
[0.0334631838 0.0333356857 0.373908311 0.559292853]
18/18 [==============================] - 0s 1ms/sample - loss: 0.0248
Epoch 1144/5000
[0.033422254 0.0332953259 0.373803556 0.559478879]
18/18 [==============================] - 0s 340us/sample - loss: 0.0247
Epoch 1145/5000
[0.0333813913 0.033255022 0.373698562 0.559664965]
18/18 [==============================] - 0s 356us/sample - loss: 0.0247
Epoch 1146/5000
[0.03334061

Epoch 1198/5000
[0.0313085951 0.0312086791 0.36797452 0.569508135]
18/18 [==============================] - 0s 347us/sample - loss: 0.0245
Epoch 1199/5000
[0.0312711596 0.0311716795 0.367863536 0.569693565]
18/18 [==============================] - 0s 346us/sample - loss: 0.0245
Epoch 1200/5000
[0.0312337689 0.0311347358 0.367752582 0.569878876]
18/18 [==============================] - 0s 378us/sample - loss: 0.0245
Epoch 1201/5000
[0.0311964378 0.0310978424 0.367641479 0.570064247]
18/18 [==============================] - 0s 339us/sample - loss: 0.0245
Epoch 1202/5000
[0.0311591849 0.0310610197 0.367530197 0.570249557]
18/18 [==============================] - 0s 336us/sample - loss: 0.0245
Epoch 1203/5000
[0.0311219823 0.0310242437 0.367418975 0.570434809]
18/18 [==============================] - 0s 361us/sample - loss: 0.0245
Epoch 1204/5000
[0.0310848262 0.0309875142 0.367307454 0.57062012]
18/18 [==============================] - 0s 339us/sample - loss: 0.0245
Epoch 1205/5000
[0.031

Epoch 1257/5000
[0.0291958321 0.0291181318 0.361270756 0.580415308]
18/18 [==============================] - 0s 359us/sample - loss: 0.0242
Epoch 1258/5000
[0.0291616246 0.0290842373 0.361154616 0.580599487]
18/18 [==============================] - 0s 332us/sample - loss: 0.0242
Epoch 1259/5000
[0.0291274637 0.0290503986 0.361038268 0.580783904]
18/18 [==============================] - 0s 339us/sample - loss: 0.0242
Epoch 1260/5000
[0.0290933456 0.0290165991 0.360921919 0.580968142]
18/18 [==============================] - 0s 345us/sample - loss: 0.0242
Epoch 1261/5000
[0.0290593058 0.0289828628 0.360805571 0.58115232]
18/18 [==============================] - 0s 332us/sample - loss: 0.0242
Epoch 1262/5000
[0.0290252976 0.0289491713 0.360688984 0.581336558]
18/18 [==============================] - 0s 346us/sample - loss: 0.0242
Epoch 1263/5000
[0.028991336 0.0289155263 0.360572398 0.581520736]
18/18 [==============================] - 0s 363us/sample - loss: 0.0242
Epoch 1264/5000
[0.028

Epoch 1316/5000
[0.0272599552 0.027197944 0.354290754 0.591251373]
18/18 [==============================] - 0s 336us/sample - loss: 0.0240
Epoch 1317/5000
[0.0272285137 0.0271667223 0.354170501 0.5914343]
18/18 [==============================] - 0s 349us/sample - loss: 0.0240
Epoch 1318/5000
[0.0271971151 0.0271355417 0.354050159 0.591617227]
18/18 [==============================] - 0s 356us/sample - loss: 0.0240
Epoch 1319/5000
[0.0271657631 0.0271043926 0.353929669 0.591800153]
18/18 [==============================] - 0s 361us/sample - loss: 0.0240
Epoch 1320/5000
[0.0271344427 0.0270732865 0.353809208 0.591983]
18/18 [==============================] - 0s 354us/sample - loss: 0.0240
Epoch 1321/5000
[0.0271031726 0.0270422287 0.353688747 0.592165887]
18/18 [==============================] - 0s 367us/sample - loss: 0.0240
Epoch 1322/5000
[0.0270719584 0.0270112138 0.353568166 0.592348695]
18/18 [==============================] - 0s 343us/sample - loss: 0.0240
Epoch 1323/5000
[0.0270407

Epoch 1375/5000
[0.0254750103 0.0254232734 0.347100288 0.602001488]
18/18 [==============================] - 0s 356us/sample - loss: 0.0238
Epoch 1376/5000
[0.0254459139 0.0253943205 0.346976876 0.602182865]
18/18 [==============================] - 0s 1ms/sample - loss: 0.0238
Epoch 1377/5000
[0.0254168566 0.0253653917 0.346853524 0.602364302]
18/18 [==============================] - 0s 371us/sample - loss: 0.0238
Epoch 1378/5000
[0.0253878441 0.0253365077 0.34673 0.602545679]
18/18 [==============================] - 0s 350us/sample - loss: 0.0238
Epoch 1379/5000
[0.0253588576 0.0253076572 0.346606523 0.602726936]
18/18 [==============================] - 0s 353us/sample - loss: 0.0238
Epoch 1380/5000
[0.0253299084 0.0252788384 0.346483082 0.602908194]
18/18 [==============================] - 0s 342us/sample - loss: 0.0238
Epoch 1381/5000
[0.0253010038 0.0252500642 0.346359432 0.603089452]
18/18 [==============================] - 0s 363us/sample - loss: 0.0238
Epoch 1382/5000
[0.0252721

Epoch 1434/5000
[0.0238176584 0.0237719119 0.339754045 0.612656355]
18/18 [==============================] - 0s 363us/sample - loss: 0.0237
Epoch 1435/5000
[0.0237905346 0.0237448495 0.339628428 0.612836182]
18/18 [==============================] - 0s 361us/sample - loss: 0.0237
Epoch 1436/5000
[0.0237634499 0.0237178411 0.339502782 0.61301595]
18/18 [==============================] - 0s 372us/sample - loss: 0.0237
Epoch 1437/5000
[0.0237364 0.0236908533 0.339377165 0.613195598]
18/18 [==============================] - 0s 354us/sample - loss: 0.0237
Epoch 1438/5000
[0.023709381 0.0236639082 0.339251459 0.613375247]
18/18 [==============================] - 0s 346us/sample - loss: 0.0236
Epoch 1439/5000
[0.0236823857 0.0236369763 0.339125752 0.613554835]
18/18 [==============================] - 0s 351us/sample - loss: 0.0236
Epoch 1440/5000
[0.0236554109 0.0236100778 0.339 0.613734484]
18/18 [==============================] - 0s 356us/sample - loss: 0.0236
Epoch 1441/5000
[0.0236284807 0

[0.0222667 0.0222236011 0.332295448 0.623214245]
18/18 [==============================] - 0s 334us/sample - loss: 0.0235
Epoch 1494/5000
[0.0222412143 0.0221981406 0.332168281 0.623392403]
18/18 [==============================] - 0s 337us/sample - loss: 0.0235
Epoch 1495/5000
[0.0222157463 0.0221726876 0.332041055 0.623570502]
18/18 [==============================] - 0s 2ms/sample - loss: 0.0235
Epoch 1496/5000
[0.0221903119 0.0221472736 0.331913829 0.623748541]
18/18 [==============================] - 0s 360us/sample - loss: 0.0235
Epoch 1497/5000
[0.0221649148 0.0221218858 0.331786662 0.62392652]
18/18 [==============================] - 0s 346us/sample - loss: 0.0235
Epoch 1498/5000
[0.0221395101 0.0220965073 0.331659287 0.624104619]
18/18 [==============================] - 0s 340us/sample - loss: 0.0235
Epoch 1499/5000
[0.0221141502 0.0220711697 0.331532091 0.624282598]
18/18 [==============================] - 0s 350us/sample - loss: 0.0235
Epoch 1500/5000
[0.0220888145 0.0220458526

18/18 [==============================] - 0s 350us/sample - loss: 0.0234
Epoch 1553/5000
[0.02077833 0.0207353644 0.32463038 0.633855939]
18/18 [==============================] - 0s 367us/sample - loss: 0.0234
Epoch 1554/5000
[0.0207541753 0.0207111984 0.324502081 0.634032607]
18/18 [==============================] - 0s 445us/sample - loss: 0.0234
Epoch 1555/5000
[0.0207300354 0.0206870418 0.324373871 0.634209037]
18/18 [==============================] - 0s 431us/sample - loss: 0.0233
Epoch 1556/5000
[0.0207059104 0.0206629075 0.324245572 0.634385645]
18/18 [==============================] - 0s 408us/sample - loss: 0.0233
Epoch 1557/5000
[0.0206818189 0.0206387937 0.324117333 0.634562075]
18/18 [==============================] - 0s 344us/sample - loss: 0.0233
Epoch 1558/5000
[0.0206577368 0.0206146874 0.323988885 0.634738684]
18/18 [==============================] - 0s 350us/sample - loss: 0.0233
Epoch 1559/5000
[0.0206336714 0.0205906 0.323860556 0.634915113]
18/18 [===================

18/18 [==============================] - 0s 342us/sample - loss: 0.0232
Epoch 1612/5000
[0.0193836819 0.0193389896 0.317044079 0.644233227]
18/18 [==============================] - 0s 1ms/sample - loss: 0.0232
Epoch 1613/5000
[0.0193605348 0.0193158034 0.316915274 0.644408405]
18/18 [==============================] - 0s 367us/sample - loss: 0.0232
Epoch 1614/5000
[0.0193373933 0.0192926284 0.316786468 0.644583523]
18/18 [==============================] - 0s 342us/sample - loss: 0.0232
Epoch 1615/5000
[0.0193142779 0.0192694645 0.316657662 0.644758582]
18/18 [==============================] - 0s 352us/sample - loss: 0.0232
Epoch 1616/5000
[0.0192911699 0.0192463193 0.316528827 0.644933701]
18/18 [==============================] - 0s 328us/sample - loss: 0.0232
Epoch 1617/5000
[0.0192680787 0.0192231797 0.316399962 0.645108759]
18/18 [==============================] - 0s 356us/sample - loss: 0.0232
Epoch 1618/5000
[0.0192450043 0.0192000624 0.316271156 0.645283818]
18/18 [===============

18/18 [==============================] - 0s 352us/sample - loss: 0.0231
Epoch 1671/5000
[0.0180405788 0.0179928262 0.30944407 0.654522538]
18/18 [==============================] - 0s 348us/sample - loss: 0.0231
Epoch 1672/5000
[0.0180181768 0.0179703534 0.309315413 0.654696107]
18/18 [==============================] - 0s 335us/sample - loss: 0.0231
Epoch 1673/5000
[0.0179957747 0.0179478973 0.309186727 0.654869556]
18/18 [==============================] - 0s 367us/sample - loss: 0.0231
Epoch 1674/5000
[0.017973382 0.0179254394 0.3090581 0.655043]
18/18 [==============================] - 0s 355us/sample - loss: 0.0231
Epoch 1675/5000
[0.0179510098 0.0179030076 0.308929443 0.655216515]
18/18 [==============================] - 0s 363us/sample - loss: 0.0231
Epoch 1676/5000
[0.0179286469 0.0178805757 0.308800906 0.655389905]
18/18 [==============================] - 0s 1ms/sample - loss: 0.0231
Epoch 1677/5000
[0.0179062895 0.0178581588 0.308672339 0.655563235]
18/18 [======================

Epoch 1730/5000
[0.0167345088 0.0166826695 0.30188635 0.664696515]
18/18 [==============================] - 0s 347us/sample - loss: 0.0230
Epoch 1731/5000
[0.0167126171 0.0166606978 0.301759154 0.66486758]
18/18 [==============================] - 0s 1ms/sample - loss: 0.0230
Epoch 1732/5000
[0.0166907348 0.016638739 0.301631957 0.665038586]
18/18 [==============================] - 0s 358us/sample - loss: 0.0230
Epoch 1733/5000
[0.0166688617 0.0166168 0.301504821 0.665209591]
18/18 [==============================] - 0s 482us/sample - loss: 0.0230
Epoch 1734/5000
[0.016647 0.0165948533 0.301377684 0.665380418]
18/18 [==============================] - 0s 372us/sample - loss: 0.0230
Epoch 1735/5000
[0.0166251436 0.0165729187 0.301250607 0.665551364]
18/18 [==============================] - 0s 347us/sample - loss: 0.0230
Epoch 1736/5000
[0.016603291 0.0165509861 0.301123619 0.665722072]
18/18 [==============================] - 0s 352us/sample - loss: 0.0230
Epoch 1737/5000
[0.0165814385 0.0

Epoch 1789/5000
[0.0154544432 0.0153977443 0.294471413 0.674676418]
18/18 [==============================] - 0s 349us/sample - loss: 0.0229
Epoch 1790/5000
[0.0154329343 0.0153761422 0.294347882 0.674843]
18/18 [==============================] - 0s 372us/sample - loss: 0.0229
Epoch 1791/5000
[0.0154114217 0.0153545439 0.294224322 0.675009727]
18/18 [==============================] - 0s 347us/sample - loss: 0.0229
Epoch 1792/5000
[0.0153899165 0.015332954 0.29410091 0.675176203]
18/18 [==============================] - 0s 351us/sample - loss: 0.0229
Epoch 1793/5000
[0.0153684122 0.0153113576 0.293977559 0.675342679]
18/18 [==============================] - 0s 337us/sample - loss: 0.0229
Epoch 1794/5000
[0.0153469285 0.0152897788 0.293854445 0.675508857]
18/18 [==============================] - 0s 356us/sample - loss: 0.0229
Epoch 1795/5000
[0.0153254364 0.0152681964 0.293731242 0.675675094]
18/18 [==============================] - 0s 1ms/sample - loss: 0.0229
Epoch 1796/5000
[0.01530395

Epoch 1848/5000
[0.0141946161 0.014132401 0.28736788 0.684305131]
18/18 [==============================] - 0s 1ms/sample - loss: 0.0228
Epoch 1849/5000
[0.0141734229 0.0141111184 0.287251502 0.684463918]
18/18 [==============================] - 0s 347us/sample - loss: 0.0228
Epoch 1850/5000
[0.0141522456 0.0140898405 0.287135273 0.684622645]
18/18 [==============================] - 0s 359us/sample - loss: 0.0228
Epoch 1851/5000
[0.0141310832 0.0140685774 0.287019223 0.684781075]
18/18 [==============================] - 0s 387us/sample - loss: 0.0228
Epoch 1852/5000
[0.014109917 0.0140473116 0.286903322 0.684939444]
18/18 [==============================] - 0s 357us/sample - loss: 0.0228
Epoch 1853/5000
[0.0140887517 0.0140260486 0.28678757 0.685097635]
18/18 [==============================] - 0s 363us/sample - loss: 0.0228
Epoch 1854/5000
[0.0140676033 0.0140048023 0.286672056 0.685255587]
18/18 [==============================] - 0s 364us/sample - loss: 0.0228
Epoch 1855/5000
[0.0140464

Epoch 1907/5000
[0.0129560586 0.0128878653 0.280828536 0.693327546]
18/18 [==============================] - 0s 348us/sample - loss: 0.0227
Epoch 1908/5000
[0.0129352883 0.0128669888 0.280724376 0.693473279]
18/18 [==============================] - 0s 340us/sample - loss: 0.0227
Epoch 1909/5000
[0.0129145328 0.0128461281 0.280620515 0.693618834]
18/18 [==============================] - 0s 357us/sample - loss: 0.0227
Epoch 1910/5000
[0.0128937792 0.012825272 0.280516893 0.693764091]
18/18 [==============================] - 0s 461us/sample - loss: 0.0227
Epoch 1911/5000
[0.0128730265 0.0128044179 0.280413449 0.693909168]
18/18 [==============================] - 0s 370us/sample - loss: 0.0227
Epoch 1912/5000
[0.0128522888 0.0127835721 0.280310392 0.694053769]
18/18 [==============================] - 0s 345us/sample - loss: 0.0227
Epoch 1913/5000
[0.0128315687 0.0127627477 0.280207634 0.694198132]
18/18 [==============================] - 0s 353us/sample - loss: 0.0227
Epoch 1914/5000
[0.01

Epoch 1966/5000
[0.0117470892 0.0116727185 0.275181323 0.701398909]
18/18 [==============================] - 0s 351us/sample - loss: 0.0226
Epoch 1967/5000
[0.0117269317 0.0116524519 0.275095433 0.701525152]
18/18 [==============================] - 0s 378us/sample - loss: 0.0226
Epoch 1968/5000
[0.0117067881 0.0116322068 0.275009841 0.701651096]
18/18 [==============================] - 0s 365us/sample - loss: 0.0226
Epoch 1969/5000
[0.0116866501 0.0116119664 0.274924666 0.701776743]
18/18 [==============================] - 0s 343us/sample - loss: 0.0226
Epoch 1970/5000
[0.0116665345 0.01159174 0.274839789 0.701901913]
18/18 [==============================] - 0s 340us/sample - loss: 0.0226
Epoch 1971/5000
[0.0116464105 0.01157152 0.27475518 0.702026904]
18/18 [==============================] - 0s 352us/sample - loss: 0.0226
Epoch 1972/5000
[0.0116263246 0.0115513317 0.274671167 0.702151179]
18/18 [==============================] - 0s 357us/sample - loss: 0.0226
Epoch 1973/5000
[0.011606

Epoch 2025/5000
[0.0105819218 0.0105015952 0.270784348 0.708132088]
18/18 [==============================] - 0s 363us/sample - loss: 0.0225
Epoch 2026/5000
[0.0105626425 0.0104822274 0.270722538 0.708232582]
18/18 [==============================] - 0s 344us/sample - loss: 0.0225
Epoch 2027/5000
[0.0105433986 0.0104628857 0.270661205 0.708332479]
18/18 [==============================] - 0s 354us/sample - loss: 0.0225
Epoch 2028/5000
[0.0105241537 0.0104435487 0.270600349 0.708431959]
18/18 [==============================] - 0s 1ms/sample - loss: 0.0225
Epoch 2029/5000
[0.0105049349 0.0104242284 0.27053991 0.708530903]
18/18 [==============================] - 0s 370us/sample - loss: 0.0225
Epoch 2030/5000
[0.0104857339 0.010404937 0.270479977 0.70862931]
18/18 [==============================] - 0s 361us/sample - loss: 0.0225
Epoch 2031/5000
[0.0104665523 0.0103856549 0.270420462 0.70872736]
18/18 [==============================] - 0s 353us/sample - loss: 0.0225
Epoch 2032/5000
[0.0104473

Epoch 2084/5000
[0.00947755575 0.00939206406 0.267951697 0.713178694]
18/18 [==============================] - 0s 353us/sample - loss: 0.0225
Epoch 2085/5000
[0.00945946202 0.00937388837 0.267918438 0.713248253]
18/18 [==============================] - 0s 352us/sample - loss: 0.0224
Epoch 2086/5000
[0.00944139 0.0093557341 0.267885804 0.713317096]
18/18 [==============================] - 0s 362us/sample - loss: 0.0224
Epoch 2087/5000
[0.00942333136 0.00933760777 0.267853647 0.713385463]
18/18 [==============================] - 0s 348us/sample - loss: 0.0224
Epoch 2088/5000
[0.00940530468 0.0093195 0.267821938 0.713453293]
18/18 [==============================] - 0s 368us/sample - loss: 0.0224
Epoch 2089/5000
[0.00938729849 0.00930141937 0.267790914 0.713520408]
18/18 [==============================] - 0s 348us/sample - loss: 0.0224
Epoch 2090/5000
[0.00936931372 0.00928335916 0.267760217 0.713587165]
18/18 [==============================] - 0s 382us/sample - loss: 0.0224
Epoch 2091/500

18/18 [==============================] - 0s 332us/sample - loss: 0.0224
Epoch 2143/5000
[0.00845009089 0.00836075284 0.266874492 0.716314614]
18/18 [==============================] - 0s 343us/sample - loss: 0.0224
Epoch 2144/5000
[0.00843341649 0.00834403187 0.26687181 0.716350734]
18/18 [==============================] - 0s 344us/sample - loss: 0.0224
Epoch 2145/5000
[0.00841676351 0.00832732487 0.266869426 0.716386497]
18/18 [==============================] - 0s 334us/sample - loss: 0.0224
Epoch 2146/5000
[0.00840014126 0.00831065 0.266867697 0.716421485]
18/18 [==============================] - 0s 2ms/sample - loss: 0.0224
Epoch 2147/5000
[0.00838353951 0.00829400774 0.266866446 0.716456]
18/18 [==============================] - 0s 393us/sample - loss: 0.0224
Epoch 2148/5000
[0.00836697407 0.00827739 0.26686576 0.716489851]
18/18 [==============================] - 0s 365us/sample - loss: 0.0224
Epoch 2149/5000
[0.0083504254 0.00826079 0.266865492 0.716523349]
18/18 [================

Epoch 2201/5000
[0.00752668036 0.00743529 0.267542571 0.717495441]
18/18 [==============================] - 0s 369us/sample - loss: 0.0223
Epoch 2202/5000
[0.00751155 0.00742014451 0.267568409 0.717499852]
18/18 [==============================] - 0s 359us/sample - loss: 0.0223
Epoch 2203/5000
[0.00749645568 0.00740502216 0.267594695 0.717503846]
18/18 [==============================] - 0s 390us/sample - loss: 0.0223
Epoch 2204/5000
[0.00748138595 0.00738994265 0.267621487 0.717507243]
18/18 [==============================] - 0s 353us/sample - loss: 0.0223
Epoch 2205/5000
[0.00746634835 0.00737488177 0.267648637 0.717510164]
18/18 [==============================] - 0s 358us/sample - loss: 0.0223
Epoch 2206/5000
[0.00745133543 0.00735985581 0.267676353 0.717512488]
18/18 [==============================] - 0s 342us/sample - loss: 0.0223
Epoch 2207/5000
[0.00743635651 0.00734485406 0.267704546 0.717514217]
18/18 [==============================] - 0s 366us/sample - loss: 0.0223
Epoch 2208/5

[0.00669536786 0.00660378858 0.269761056 0.716939807]
18/18 [==============================] - 0s 341us/sample - loss: 0.0223
Epoch 2260/5000
[0.00668185437 0.00659028674 0.269811332 0.716916502]
18/18 [==============================] - 0s 342us/sample - loss: 0.0223
Epoch 2261/5000
[0.00666836835 0.00657681655 0.269861847 0.716892958]
18/18 [==============================] - 0s 1ms/sample - loss: 0.0223
Epoch 2262/5000
[0.00665491307 0.00656337338 0.26991272 0.716869]
18/18 [==============================] - 0s 351us/sample - loss: 0.0223
Epoch 2263/5000
[0.00664147921 0.00654995907 0.269964 0.716844559]
18/18 [==============================] - 0s 346us/sample - loss: 0.0223
Epoch 2264/5000
[0.00662807561 0.00653656805 0.270015597 0.716819704]
18/18 [==============================] - 0s 322us/sample - loss: 0.0223
Epoch 2265/5000
[0.00661470648 0.00652321288 0.270067781 0.716794312]
18/18 [==============================] - 0s 334us/sample - loss: 0.0223
Epoch 2266/5000
[0.00660136202 

18/18 [==============================] - 0s 365us/sample - loss: 0.0222
Epoch 2318/5000
[0.00594509346 0.0058551617 0.273283958 0.714915752]
18/18 [==============================] - 0s 500us/sample - loss: 0.0222
Epoch 2319/5000
[0.00593318697 0.00584329339 0.273352176 0.714871347]
18/18 [==============================] - 0s 373us/sample - loss: 0.0222
Epoch 2320/5000
[0.0059213154 0.00583146233 0.273420721 0.714826524]
18/18 [==============================] - 0s 327us/sample - loss: 0.0222
Epoch 2321/5000
[0.00590946572 0.00581966 0.273489594 0.714781284]
18/18 [==============================] - 0s 278us/sample - loss: 0.0222
Epoch 2322/5000
[0.00589764072 0.00580787566 0.273558468 0.714736044]
18/18 [==============================] - 0s 266us/sample - loss: 0.0222
Epoch 2323/5000
[0.00588584365 0.0057961233 0.273627698 0.714690328]
18/18 [==============================] - 0s 303us/sample - loss: 0.0222
Epoch 2324/5000
[0.00587407 0.00578439608 0.273697227 0.714644253]
18/18 [========

Epoch 2376/5000
[0.00529769948 0.00521090766 0.277565211 0.711926162]
18/18 [==============================] - 0s 354us/sample - loss: 0.0222
Epoch 2377/5000
[0.00528728543 0.00520055508 0.277643293 0.711868882]
18/18 [==============================] - 0s 352us/sample - loss: 0.0222
Epoch 2378/5000
[0.00527689792 0.00519023417 0.277721643 0.711811185]
18/18 [==============================] - 0s 335us/sample - loss: 0.0222
Epoch 2379/5000
[0.00526653184 0.00517993467 0.277799934 0.711753547]
18/18 [==============================] - 0s 351us/sample - loss: 0.0222
Epoch 2380/5000
[0.0052561895 0.00516965846 0.277878404 0.711695731]
18/18 [==============================] - 0s 347us/sample - loss: 0.0222
Epoch 2381/5000
[0.00524587324 0.00515940925 0.277957 0.711637676]
18/18 [==============================] - 0s 330us/sample - loss: 0.0222
Epoch 2382/5000
[0.00523558073 0.00514918333 0.27803576 0.711579442]
18/18 [==============================] - 0s 337us/sample - loss: 0.0222
Epoch 2383/

[0.00473312754 0.00465060351 0.282193869 0.708422363]
18/18 [==============================] - 0s 339us/sample - loss: 0.0222
Epoch 2435/5000
[0.00472407369 0.00464162836 0.282274276 0.708360076]
18/18 [==============================] - 0s 341us/sample - loss: 0.0222
Epoch 2436/5000
[0.00471504172 0.00463267928 0.282354474 0.708297849]
18/18 [==============================] - 0s 341us/sample - loss: 0.0221
Epoch 2437/5000
[0.00470602931 0.00462375162 0.282434613 0.708235621]
18/18 [==============================] - 0s 348us/sample - loss: 0.0221
Epoch 2438/5000
[0.00469704112 0.00461484306 0.282514721 0.708173335]
18/18 [==============================] - 0s 1ms/sample - loss: 0.0221
Epoch 2439/5000
[0.00468807854 0.00460596057 0.282594889 0.708111048]
18/18 [==============================] - 0s 361us/sample - loss: 0.0221
Epoch 2440/5000
[0.00467913132 0.00459709531 0.282674938 0.70804882]
18/18 [==============================] - 0s 359us/sample - loss: 0.0221
Epoch 2441/5000
[0.004670

18/18 [==============================] - 0s 351us/sample - loss: 0.0221
Epoch 2493/5000
[0.00423535239 0.00415791944 0.286820829 0.704785943]
18/18 [==============================] - 0s 356us/sample - loss: 0.0221
Epoch 2494/5000
[0.00422752928 0.00415018806 0.286896586 0.704725683]
18/18 [==============================] - 0s 366us/sample - loss: 0.0221
Epoch 2495/5000
[0.00421972 0.00414246647 0.286971807 0.704666]
18/18 [==============================] - 0s 366us/sample - loss: 0.0221
Epoch 2496/5000
[0.00421193708 0.00413477654 0.287047207 0.704606056]
18/18 [==============================] - 0s 375us/sample - loss: 0.0221
Epoch 2497/5000
[0.00420417218 0.00412710058 0.287122458 0.704546273]
18/18 [==============================] - 0s 361us/sample - loss: 0.0221
Epoch 2498/5000
[0.0041964245 0.00411944184 0.287197381 0.704486728]
18/18 [==============================] - 0s 353us/sample - loss: 0.0221
Epoch 2499/5000
[0.00418869453 0.004111805 0.287272424 0.704427063]
18/18 [========

Epoch 2551/5000
[0.00381233683 0.003740279 0.290961683 0.701485693]
18/18 [==============================] - 0s 353us/sample - loss: 0.0221
Epoch 2552/5000
[0.00380556425 0.00373360259 0.291028172 0.701432586]
18/18 [==============================] - 0s 357us/sample - loss: 0.0221
Epoch 2553/5000
[0.00379881519 0.00372694572 0.291094691 0.701379538]
18/18 [==============================] - 0s 349us/sample - loss: 0.0221
Epoch 2554/5000
[0.0037920808 0.00372030516 0.291160882 0.701326728]
18/18 [==============================] - 0s 930us/sample - loss: 0.0221
Epoch 2555/5000
[0.0037853634 0.00371368113 0.291226864 0.701274097]
18/18 [==============================] - 0s 354us/sample - loss: 0.0221
Epoch 2556/5000
[0.00377865834 0.00370707316 0.291292667 0.701221645]
18/18 [==============================] - 0s 355us/sample - loss: 0.0221
Epoch 2557/5000
[0.00377197657 0.00370048452 0.291358262 0.701169252]
18/18 [==============================] - 0s 346us/sample - loss: 0.0221
Epoch 2558

18/18 [==============================] - 0s 373us/sample - loss: 0.0221
Epoch 2610/5000
[0.00344052794 0.00337401917 0.294568956 0.698616505]
18/18 [==============================] - 0s 363us/sample - loss: 0.0221
Epoch 2611/5000
[0.00343468576 0.00336826569 0.294624299 0.698572814]
18/18 [==============================] - 0s 344us/sample - loss: 0.0221
Epoch 2612/5000
[0.00342885661 0.00336253177 0.294679552 0.698529124]
18/18 [==============================] - 0s 365us/sample - loss: 0.0221
Epoch 2613/5000
[0.00342304609 0.00335681438 0.294734597 0.698485553]
18/18 [==============================] - 0s 344us/sample - loss: 0.0221
Epoch 2614/5000
[0.00341724 0.00335110142 0.294789433 0.698442221]
18/18 [==============================] - 0s 373us/sample - loss: 0.0221
Epoch 2615/5000
[0.00341145648 0.0033454122 0.294844031 0.698399127]
18/18 [==============================] - 0s 345us/sample - loss: 0.0221
Epoch 2616/5000
[0.00340568414 0.00333973276 0.294898599 0.698356032]
18/18 [===

Epoch 2668/5000
[0.00312435348 0.00306316302 0.297470629 0.696341813]
18/18 [==============================] - 0s 410us/sample - loss: 0.0221
Epoch 2669/5000
[0.00311928452 0.0030581851 0.297515243 0.696307302]
18/18 [==============================] - 0s 361us/sample - loss: 0.0221
Epoch 2670/5000
[0.00311423023 0.00305322232 0.297559798 0.69627279]
18/18 [==============================] - 0s 353us/sample - loss: 0.0221
Epoch 2671/5000
[0.00310919154 0.00304827094 0.297604203 0.696238339]
18/18 [==============================] - 0s 345us/sample - loss: 0.0221
Epoch 2672/5000
[0.00310416287 0.0030433333 0.297648221 0.696204245]
18/18 [==============================] - 0s 1ms/sample - loss: 0.0221
Epoch 2673/5000
[0.00309914281 0.00303840311 0.29769215 0.69617033]
18/18 [==============================] - 0s 357us/sample - loss: 0.0221
Epoch 2674/5000
[0.00309413834 0.00303348643 0.297735661 0.696136713]
18/18 [==============================] - 0s 358us/sample - loss: 0.0221
Epoch 2675/50

[0.0028498 0.00279367552 0.29978317 0.694573343]
18/18 [==============================] - 0s 1ms/sample - loss: 0.0220
Epoch 2727/5000
[0.00284539186 0.00278935116 0.299818575 0.6945467]
18/18 [==============================] - 0s 349us/sample - loss: 0.0220
Epoch 2728/5000
[0.00284099462 0.00278503797 0.299853504 0.694520414]
18/18 [==============================] - 0s 362us/sample - loss: 0.0220
Epoch 2729/5000
[0.00283661019 0.00278073968 0.299888462 0.694494188]
18/18 [==============================] - 0s 417us/sample - loss: 0.0220
Epoch 2730/5000
[0.00283223181 0.00277644536 0.29992339 0.694467902]
18/18 [==============================] - 0s 395us/sample - loss: 0.0220
Epoch 2731/5000
[0.00282786693 0.0027721636 0.29995805 0.694441915]
18/18 [==============================] - 0s 345us/sample - loss: 0.0220
Epoch 2732/5000
[0.00282351207 0.00276789325 0.299992532 0.694416046]
18/18 [==============================] - 0s 362us/sample - loss: 0.0220
Epoch 2733/5000
[0.00281916605 0.0

18/18 [==============================] - 0s 359us/sample - loss: 0.0220
Epoch 2785/5000
[0.00260668388 0.00255537033 0.30163309 0.69320488]
18/18 [==============================] - 0s 351us/sample - loss: 0.0220
Epoch 2786/5000
[0.00260284264 0.00255160453 0.301660746 0.693184793]
18/18 [==============================] - 0s 344us/sample - loss: 0.0220
Epoch 2787/5000
[0.00259901211 0.00254785432 0.301688343 0.693164766]
18/18 [==============================] - 0s 357us/sample - loss: 0.0220
Epoch 2788/5000
[0.0025951874 0.00254410622 0.301715553 0.693145156]
18/18 [==============================] - 0s 339us/sample - loss: 0.0220
Epoch 2789/5000
[0.0025913713 0.00254036975 0.301743031 0.693125248]
18/18 [==============================] - 0s 345us/sample - loss: 0.0220
Epoch 2790/5000
[0.00258756941 0.00253664679 0.301770389 0.693105459]
18/18 [==============================] - 0s 1ms/sample - loss: 0.0220
Epoch 2791/5000
[0.00258376915 0.00253292476 0.30179745 0.693085849]
18/18 [======

Epoch 2843/5000
[0.00239772745 0.0023507739 0.303068519 0.692183]
18/18 [==============================] - 0s 381us/sample - loss: 0.0220
Epoch 2844/5000
[0.00239435653 0.00234747445 0.303090543 0.69216764]
18/18 [==============================] - 0s 372us/sample - loss: 0.0220
Epoch 2845/5000
[0.00239099259 0.00234418316 0.303112447 0.692152321]
18/18 [==============================] - 0s 359us/sample - loss: 0.0220
Epoch 2846/5000
[0.0023876382 0.00234090141 0.303134322 0.692137122]
18/18 [==============================] - 0s 345us/sample - loss: 0.0220
Epoch 2847/5000
[0.00238429289 0.00233762455 0.303155959 0.692122102]
18/18 [==============================] - 0s 363us/sample - loss: 0.0220
Epoch 2848/5000
[0.00238095177 0.00233435468 0.303177655 0.692107]
18/18 [==============================] - 0s 360us/sample - loss: 0.0220
Epoch 2849/5000
[0.0023776209 0.00233109551 0.3031995 0.692091823]
18/18 [==============================] - 0s 370us/sample - loss: 0.0220
Epoch 2850/5000
[0

18/18 [==============================] - 0s 360us/sample - loss: 0.0220
Epoch 2902/5000
[0.00221096538 0.00216806703 0.304238707 0.691382229]
18/18 [==============================] - 0s 361us/sample - loss: 0.0220
Epoch 2903/5000
[0.00220799726 0.0021651648 0.304256558 0.691370308]
18/18 [==============================] - 0s 342us/sample - loss: 0.0220
Epoch 2904/5000
[0.00220503774 0.00216227188 0.304274231 0.691358447]
18/18 [==============================] - 0s 350us/sample - loss: 0.0220
Epoch 2905/5000
[0.00220208382 0.00215938245 0.304292 0.691346526]
18/18 [==============================] - 0s 1ms/sample - loss: 0.0220
Epoch 2906/5000
[0.00219913945 0.0021565014 0.304309696 0.691334665]
18/18 [==============================] - 0s 356us/sample - loss: 0.0220
Epoch 2907/5000
[0.0021961981 0.00215362734 0.304327279 0.691322863]
18/18 [==============================] - 0s 343us/sample - loss: 0.0220
Epoch 2908/5000
[0.00219326373 0.00215075607 0.304344565 0.691311359]
18/18 [=======

Epoch 2960/5000
[0.00204882049 0.002009555 0.305179775 0.690761864]
18/18 [==============================] - 0s 347us/sample - loss: 0.0220
Epoch 2961/5000
[0.00204619695 0.00200698827 0.305194855 0.69075197]
18/18 [==============================] - 0s 348us/sample - loss: 0.0220
Epoch 2962/5000
[0.00204357086 0.00200442318 0.305209309 0.690742671]
18/18 [==============================] - 0s 356us/sample - loss: 0.0220
Epoch 2963/5000
[0.00204095221 0.00200186204 0.305224031 0.690733075]
18/18 [==============================] - 0s 339us/sample - loss: 0.0220
Epoch 2964/5000
[0.00203834032 0.00199931068 0.305238664 0.690723658]
18/18 [==============================] - 0s 339us/sample - loss: 0.0220
Epoch 2965/5000
[0.00203573308 0.00199676212 0.305253357 0.690714121]
18/18 [==============================] - 0s 332us/sample - loss: 0.0220
Epoch 2966/5000
[0.0020331312 0.00199421751 0.305267811 0.690704823]
18/18 [==============================] - 0s 346us/sample - loss: 0.0220
Epoch 2967

Epoch 3018/5000
[0.00190474442 0.00186877639 0.305967718 0.690258801]
18/18 [==============================] - 0s 343us/sample - loss: 0.0220
Epoch 3019/5000
[0.00190240389 0.00186648895 0.305980057 0.690251052]
18/18 [==============================] - 0s 339us/sample - loss: 0.0220
Epoch 3020/5000
[0.00190006476 0.0018642029 0.305992663 0.690243125]
18/18 [==============================] - 0s 328us/sample - loss: 0.0220
Epoch 3021/5000
[0.00189773168 0.00186192454 0.306005031 0.690235317]
18/18 [==============================] - 0s 336us/sample - loss: 0.0220
Epoch 3022/5000
[0.00189540535 0.00185965374 0.306017637 0.69022733]
18/18 [==============================] - 0s 552us/sample - loss: 0.0220
Epoch 3023/5000
[0.0018930838 0.00185738376 0.306029826 0.690219641]
18/18 [==============================] - 0s 1ms/sample - loss: 0.0220
Epoch 3024/5000
[0.00189076061 0.00185511517 0.306042075 0.690212071]
18/18 [==============================] - 0s 349us/sample - loss: 0.0220
Epoch 3025/

Epoch 3076/5000
[0.00177608035 0.00174310128 0.306639433 0.68984139]
18/18 [==============================] - 0s 403us/sample - loss: 0.0220
Epoch 3077/5000
[0.00177398266 0.00174105586 0.306650221 0.689834714]
18/18 [==============================] - 0s 1ms/sample - loss: 0.0220
Epoch 3078/5000
[0.00177189184 0.00173901266 0.306661069 0.689828038]
18/18 [==============================] - 0s 359us/sample - loss: 0.0220
Epoch 3079/5000
[0.00176980346 0.00173697388 0.306671798 0.689821422]
18/18 [==============================] - 0s 341us/sample - loss: 0.0220
Epoch 3080/5000
[0.00176771812 0.00173493719 0.306682408 0.689815]
18/18 [==============================] - 0s 351us/sample - loss: 0.0220
Epoch 3081/5000
[0.00176563766 0.00173290446 0.306692898 0.689808547]
18/18 [==============================] - 0s 336us/sample - loss: 0.0220
Epoch 3082/5000
[0.00176355953 0.00173087639 0.306703538 0.689802051]
18/18 [==============================] - 0s 353us/sample - loss: 0.0220
Epoch 3083/5

18/18 [==============================] - 0s 354us/sample - loss: 0.0220
Epoch 3135/5000
[0.00165874686 0.00162852951 0.307230741 0.689482]
18/18 [==============================] - 0s 345us/sample - loss: 0.0220
Epoch 3136/5000
[0.00165686244 0.00162669271 0.307240278 0.689476132]
18/18 [==============================] - 0s 372us/sample - loss: 0.0220
Epoch 3137/5000
[0.00165498583 0.00162485789 0.307249486 0.689470649]
18/18 [==============================] - 0s 353us/sample - loss: 0.0220
Epoch 3138/5000
[0.00165310875 0.00162302586 0.307258755 0.689465106]
18/18 [==============================] - 0s 349us/sample - loss: 0.0220
Epoch 3139/5000
[0.00165123609 0.00162119733 0.307268113 0.689459503]
18/18 [==============================] - 0s 353us/sample - loss: 0.0220
Epoch 3140/5000
[0.00164936739 0.00161937182 0.307277292 0.689453959]
18/18 [==============================] - 0s 340us/sample - loss: 0.0220
Epoch 3141/5000
[0.0016475016 0.0016175491 0.307286441 0.689448476]
18/18 [====

Epoch 3193/5000
[0.00155487 0.00152711011 0.307739943 0.68917805]
18/18 [==============================] - 0s 336us/sample - loss: 0.0220
Epoch 3194/5000
[0.00155317038 0.00152545155 0.307748228 0.689173162]
18/18 [==============================] - 0s 1ms/sample - loss: 0.0220
Epoch 3195/5000
[0.00155146979 0.00152379228 0.307756335 0.689168453]
18/18 [==============================] - 0s 360us/sample - loss: 0.0220
Epoch 3196/5000
[0.00154977711 0.00152213988 0.307764649 0.689163387]
18/18 [==============================] - 0s 360us/sample - loss: 0.0220
Epoch 3197/5000
[0.00154808385 0.00152048713 0.307772785 0.689158618]
18/18 [==============================] - 0s 359us/sample - loss: 0.0220
Epoch 3198/5000
[0.00154639431 0.00151883624 0.307780772 0.689154]
18/18 [==============================] - 0s 336us/sample - loss: 0.0220
Epoch 3199/5000
[0.00154470885 0.00151719095 0.307789 0.689149082]
18/18 [==============================] - 0s 451us/sample - loss: 0.0220
Epoch 3200/5000
[0

[0.00146084174 0.00143531326 0.308190882 0.688913]
18/18 [==============================] - 0s 358us/sample - loss: 0.0220
Epoch 3252/5000
[0.00145929842 0.00143380801 0.308198 0.688908875]
18/18 [==============================] - 0s 343us/sample - loss: 0.0220
Epoch 3253/5000
[0.00145775743 0.00143230264 0.308205277 0.688904643]
18/18 [==============================] - 0s 342us/sample - loss: 0.0220
Epoch 3254/5000
[0.00145622157 0.00143080333 0.308212519 0.688900471]
18/18 [==============================] - 0s 341us/sample - loss: 0.0220
Epoch 3255/5000
[0.00145468523 0.00142930378 0.30821982 0.688896239]
18/18 [==============================] - 0s 337us/sample - loss: 0.0220
Epoch 3256/5000
[0.00145314948 0.00142780587 0.308227152 0.688891947]
18/18 [==============================] - 0s 2ms/sample - loss: 0.0220
Epoch 3257/5000
[0.00145162211 0.001426314 0.308234394 0.688887596]
18/18 [==============================] - 0s 393us/sample - loss: 0.0220
Epoch 3258/5000
[0.00145009416 0.

18/18 [==============================] - 0s 2ms/sample - loss: 0.0220
Epoch 3310/5000
[0.00137397612 0.00135051215 0.308599621 0.68867588]
18/18 [==============================] - 0s 365us/sample - loss: 0.0220
Epoch 3311/5000
[0.00137257308 0.00134914345 0.308606118 0.688672125]
18/18 [==============================] - 0s 354us/sample - loss: 0.0220
Epoch 3312/5000
[0.00137117319 0.0013477765 0.308612555 0.688668489]
18/18 [==============================] - 0s 358us/sample - loss: 0.0220
Epoch 3313/5000
[0.00136977492 0.00134640979 0.308619171 0.688664675]
18/18 [==============================] - 0s 344us/sample - loss: 0.0220
Epoch 3314/5000
[0.00136837852 0.00134504819 0.308625787 0.688660741]
18/18 [==============================] - 0s 350us/sample - loss: 0.0220
Epoch 3315/5000
[0.00136698456 0.00134368509 0.308632284 0.688657]
18/18 [==============================] - 0s 348us/sample - loss: 0.0220
Epoch 3316/5000
[0.00136559468 0.00134232966 0.308638841 0.688653231]
18/18 [======

18/18 [==============================] - 0s 763us/sample - loss: 0.0220
Epoch 3368/5000
[0.00129614491 0.00127452507 0.308960229 0.688469052]
18/18 [==============================] - 0s 399us/sample - loss: 0.0220
Epoch 3369/5000
[0.00129486341 0.00127327454 0.30896619 0.688465595]
18/18 [==============================] - 0s 340us/sample - loss: 0.0220
Epoch 3370/5000
[0.00129358307 0.00127202331 0.308971971 0.688462377]
18/18 [==============================] - 0s 365us/sample - loss: 0.0220
Epoch 3371/5000
[0.00129230367 0.00127077615 0.308977902 0.688459039]
18/18 [==============================] - 0s 357us/sample - loss: 0.0220
Epoch 3372/5000
[0.0012910295 0.00126953 0.308983862 0.688455582]
18/18 [==============================] - 0s 352us/sample - loss: 0.0220
Epoch 3373/5000
[0.00128975557 0.00126828626 0.308989584 0.688452423]
18/18 [==============================] - 0s 333us/sample - loss: 0.0220
Epoch 3374/5000
[0.00128848164 0.00126704446 0.308995426 0.688449]
18/18 [=======

Epoch 3426/5000
[0.00122490071 0.00120496261 0.309286028 0.688284039]
18/18 [==============================] - 0s 354us/sample - loss: 0.0219
Epoch 3427/5000
[0.00122372445 0.00120381406 0.309291393 0.688281059]
18/18 [==============================] - 0s 1ms/sample - loss: 0.0219
Epoch 3428/5000
[0.00122255343 0.00120266841 0.309296876 0.688277841]
18/18 [==============================] - 0s 357us/sample - loss: 0.0219
Epoch 3429/5000
[0.0012213809 0.00120152638 0.3093023 0.688274801]
18/18 [==============================] - 0s 348us/sample - loss: 0.0219
Epoch 3430/5000
[0.00122021069 0.00120038376 0.309307665 0.688271761]
18/18 [==============================] - 0s 356us/sample - loss: 0.0219
Epoch 3431/5000
[0.00121904304 0.00119924371 0.309313089 0.688268602]
18/18 [==============================] - 0s 333us/sample - loss: 0.0219
Epoch 3432/5000
[0.00121787668 0.00119810202 0.309318304 0.6882658]
18/18 [==============================] - 0s 348us/sample - loss: 0.0219
Epoch 3433/50

18/18 [==============================] - 0s 378us/sample - loss: 0.0219
Epoch 3485/5000
[0.00115840184 0.00114002381 0.309586823 0.688114762]
18/18 [==============================] - 0s 373us/sample - loss: 0.0219
Epoch 3486/5000
[0.00115732255 0.00113897037 0.3095918 0.688111842]
18/18 [==============================] - 0s 376us/sample - loss: 0.0219
Epoch 3487/5000
[0.00115624571 0.00113791716 0.309596628 0.688109159]
18/18 [==============================] - 0s 395us/sample - loss: 0.0219
Epoch 3488/5000
[0.00115516898 0.00113686605 0.309601367 0.688106537]
18/18 [==============================] - 0s 429us/sample - loss: 0.0219
Epoch 3489/5000
[0.001154094 0.00113581622 0.309606314 0.688103735]
18/18 [==============================] - 0s 362us/sample - loss: 0.0219
Epoch 3490/5000
[0.00115302019 0.00113476755 0.309611171 0.688101053]
18/18 [==============================] - 0s 362us/sample - loss: 0.0219
Epoch 3491/5000
[0.00115194835 0.00113372074 0.309616029 0.688098311]
18/18 [===

Epoch 3543/5000
[0.0010982363 0.00108126027 0.309856504 0.687964]
18/18 [==============================] - 0s 362us/sample - loss: 0.0219
Epoch 3544/5000
[0.001097242 0.00108028646 0.309860885 0.687961578]
18/18 [==============================] - 0s 362us/sample - loss: 0.0219
Epoch 3545/5000
[0.00109624641 0.00107931602 0.309865057 0.687959373]
18/18 [==============================] - 0s 359us/sample - loss: 0.0219
Epoch 3546/5000
[0.00109525432 0.00107834698 0.309869617 0.68795681]
18/18 [==============================] - 0s 350us/sample - loss: 0.0219
Epoch 3547/5000
[0.00109426328 0.00107737852 0.309874266 0.687954068]
18/18 [==============================] - 0s 385us/sample - loss: 0.0219
Epoch 3548/5000
[0.00109327352 0.00107641111 0.309878796 0.687951505]
18/18 [==============================] - 0s 360us/sample - loss: 0.0219
Epoch 3549/5000
[0.00109228387 0.00107544498 0.309883088 0.687949181]
18/18 [==============================] - 0s 363us/sample - loss: 0.0219
Epoch 3550/50

18/18 [==============================] - 0s 346us/sample - loss: 0.0219
Epoch 3602/5000
[0.00104175298 0.00102608 0.310107201 0.687824965]
18/18 [==============================] - 0s 377us/sample - loss: 0.0219
Epoch 3603/5000
[0.00104083261 0.00102518045 0.310111433 0.687822521]
18/18 [==============================] - 0s 377us/sample - loss: 0.0219
Epoch 3604/5000
[0.00103991502 0.00102428289 0.310115457 0.687820315]
18/18 [==============================] - 0s 1ms/sample - loss: 0.0219
Epoch 3605/5000
[0.00103899778 0.00102338626 0.31011942 0.68781811]
18/18 [==============================] - 0s 366us/sample - loss: 0.0219
Epoch 3606/5000
[0.00103808229 0.00102249242 0.310123473 0.687815964]
18/18 [==============================] - 0s 367us/sample - loss: 0.0219
Epoch 3607/5000
[0.0010371675 0.00102159905 0.310127616 0.68781364]
18/18 [==============================] - 0s 366us/sample - loss: 0.0219
Epoch 3608/5000
[0.00103625446 0.00102070661 0.310131699 0.687811375]
18/18 [========

18/18 [==============================] - 0s 345us/sample - loss: 0.0219
Epoch 3660/5000
[0.000990375644 0.000975873787 0.310333848 0.687699914]
18/18 [==============================] - 0s 361us/sample - loss: 0.0219
Epoch 3661/5000
[0.000989522086 0.000975040311 0.310337484 0.687697947]
18/18 [==============================] - 0s 349us/sample - loss: 0.0219
Epoch 3662/5000
[0.000988670392 0.000974209455 0.31034106 0.68769604]
18/18 [==============================] - 0s 354us/sample - loss: 0.0219
Epoch 3663/5000
[0.000987819163 0.000973377144 0.310344785 0.687693954]
18/18 [==============================] - 0s 354us/sample - loss: 0.0219
Epoch 3664/5000
[0.000986970612 0.00097254751 0.31034857 0.687691867]
18/18 [==============================] - 0s 392us/sample - loss: 0.0219
Epoch 3665/5000
[0.000986122526 0.000971718749 0.310352147 0.68768996]
18/18 [==============================] - 0s 351us/sample - loss: 0.0219
Epoch 3666/5000
[0.000985276 0.000970891 0.3103562 0.687687576]
18/18

Epoch 3717/5000
[0.000943480583 0.000930040085 0.310538948 0.687587559]
18/18 [==============================] - 0s 353us/sample - loss: 0.0219
Epoch 3718/5000
[0.000942687446 0.00092926441 0.310542434 0.687585652]
18/18 [==============================] - 0s 342us/sample - loss: 0.0219
Epoch 3719/5000
[0.000941895 0.000928490073 0.310545713 0.687583864]
18/18 [==============================] - 0s 345us/sample - loss: 0.0219
Epoch 3720/5000
[0.000941104721 0.000927716726 0.310549349 0.687581778]
18/18 [==============================] - 0s 345us/sample - loss: 0.0219
Epoch 3721/5000
[0.000940314 0.000926944369 0.310552478 0.687580228]
18/18 [==============================] - 0s 1ms/sample - loss: 0.0219
Epoch 3722/5000
[0.000939524907 0.000926173525 0.310556263 0.687578]
18/18 [==============================] - 0s 361us/sample - loss: 0.0219
Epoch 3723/5000
[0.00093873631 0.000925402273 0.310559422 0.687576413]
18/18 [==============================] - 0s 341us/sample - loss: 0.0219
Epoch

18/18 [==============================] - 0s 2ms/sample - loss: 0.0219
Epoch 3775/5000
[0.000899068604 0.000886619207 0.310732096 0.687482238]
18/18 [==============================] - 0s 360us/sample - loss: 0.0219
Epoch 3776/5000
[0.000898330123 0.000885896909 0.310735255 0.687480509]
18/18 [==============================] - 0s 338us/sample - loss: 0.0219
Epoch 3777/5000
[0.00089759304 0.00088517688 0.310738474 0.687478781]
18/18 [==============================] - 0s 357us/sample - loss: 0.0219
Epoch 3778/5000
[0.000896856887 0.000884456735 0.310741484 0.687477231]
18/18 [==============================] - 0s 352us/sample - loss: 0.0219
Epoch 3779/5000
[0.000896121317 0.00088373723 0.310744852 0.687475324]
18/18 [==============================] - 0s 362us/sample - loss: 0.0219
Epoch 3780/5000
[0.000895385048 0.000883017958 0.310747743 0.687473834]
18/18 [==============================] - 0s 358us/sample - loss: 0.0219
Epoch 3781/5000
[0.000894652 0.000882300839 0.310751081 0.687471926]


Epoch 3832/5000
[0.000858363754 0.000846811163 0.310908 0.68738687]
18/18 [==============================] - 0s 423us/sample - loss: 0.0219
Epoch 3833/5000
[0.00085767376 0.000846136536 0.310911089 0.687385082]
18/18 [==============================] - 0s 408us/sample - loss: 0.0219
Epoch 3834/5000
[0.00085698464 0.000845463073 0.310914248 0.687383235]
18/18 [==============================] - 0s 370us/sample - loss: 0.0219
Epoch 3835/5000
[0.000856297207 0.000844790135 0.310917556 0.687381327]
18/18 [==============================] - 0s 366us/sample - loss: 0.0219
Epoch 3836/5000
[0.000855609484 0.000844116847 0.310920328 0.687379956]
18/18 [==============================] - 0s 1ms/sample - loss: 0.0219
Epoch 3837/5000
[0.000854922459 0.000843445479 0.310923159 0.687378466]
18/18 [==============================] - 0s 379us/sample - loss: 0.0219
Epoch 3838/5000
[0.000854236772 0.000842775393 0.31092608 0.687376916]
18/18 [==============================] - 0s 357us/sample - loss: 0.0219
E

18/18 [==============================] - 0s 442us/sample - loss: 0.0219
Epoch 3890/5000
[0.000819658104 0.000808947603 0.311074674 0.687296748]
18/18 [==============================] - 0s 370us/sample - loss: 0.0219
Epoch 3891/5000
[0.00081901392 0.000808318087 0.311077446 0.687295198]
18/18 [==============================] - 0s 435us/sample - loss: 0.0219
Epoch 3892/5000
[0.000818370376 0.000807687175 0.311080188 0.687293708]
18/18 [==============================] - 0s 370us/sample - loss: 0.0219
Epoch 3893/5000
[0.000817725784 0.000807057484 0.311082929 0.687292218]
18/18 [==============================] - 0s 337us/sample - loss: 0.0219
Epoch 3894/5000
[0.000817083928 0.00080643018 0.31108579 0.687290668]
18/18 [==============================] - 0s 347us/sample - loss: 0.0219
Epoch 3895/5000
[0.000816441199 0.000805800431 0.311088473 0.687289238]
18/18 [==============================] - 0s 347us/sample - loss: 0.0219
Epoch 3896/5000
[0.000815800333 0.000805173244 0.311091453 0.687287

Epoch 3947/5000
[0.000784050382 0.000774104497 0.311227649 0.687214196]
18/18 [==============================] - 0s 356us/sample - loss: 0.0219
Epoch 3948/5000
[0.000783446245 0.000773513166 0.31123 0.687213]
18/18 [==============================] - 0s 362us/sample - loss: 0.0219
Epoch 3949/5000
[0.00078284234 0.000772922067 0.311232626 0.687211633]
18/18 [==============================] - 0s 354us/sample - loss: 0.0219
Epoch 3950/5000
[0.00078223797 0.000772331667 0.311235309 0.687210143]
18/18 [==============================] - 0s 503us/sample - loss: 0.0219
Epoch 3951/5000
[0.000781637209 0.000771742605 0.311237812 0.687208772]
18/18 [==============================] - 0s 1ms/sample - loss: 0.0219
Epoch 3952/5000
[0.000781034818 0.000771152554 0.311240405 0.68720746]
18/18 [==============================] - 0s 358us/sample - loss: 0.0219
Epoch 3953/5000
[0.000780433707 0.00077056489 0.311243057 0.687205911]
18/18 [==============================] - 0s 349us/sample - loss: 0.0219
Epoch

18/18 [==============================] - 0s 2ms/sample - loss: 0.0219
Epoch 4005/5000
[0.000750073232 0.00074084691 0.311372578 0.687136531]
18/18 [==============================] - 0s 442us/sample - loss: 0.0219
Epoch 4006/5000
[0.000749506231 0.000740292249 0.311374933 0.687135279]
18/18 [==============================] - 0s 394us/sample - loss: 0.0219
Epoch 4007/5000
[0.00074893987 0.000739737763 0.311377525 0.687133849]
18/18 [==============================] - 0s 341us/sample - loss: 0.0219
Epoch 4008/5000
[0.000748373801 0.000739182869 0.31137982 0.687132657]
18/18 [==============================] - 0s 346us/sample - loss: 0.0219
Epoch 4009/5000
[0.000747808139 0.000738629489 0.311382115 0.687131464]
18/18 [==============================] - 0s 346us/sample - loss: 0.0219
Epoch 4010/5000
[0.000747243816 0.000738076633 0.31138429 0.687130392]
18/18 [==============================] - 0s 372us/sample - loss: 0.0219
Epoch 4011/5000
[0.000746679725 0.000737523951 0.311386615 0.68712914]

Epoch 4062/5000
[0.000718710478 0.000710138062 0.311505735 0.687065423]
18/18 [==============================] - 0s 342us/sample - loss: 0.0219
Epoch 4063/5000
[0.000718176889 0.000709615 0.311507881 0.68706429]
18/18 [==============================] - 0s 344us/sample - loss: 0.0219
Epoch 4064/5000
[0.000717643532 0.000709092361 0.311509967 0.687063277]
18/18 [==============================] - 0s 336us/sample - loss: 0.0219
Epoch 4065/5000
[0.000717112096 0.000708572275 0.31151253 0.687061787]
18/18 [==============================] - 0s 334us/sample - loss: 0.0219
Epoch 4066/5000
[0.000716580427 0.000708050968 0.311514705 0.687060654]
18/18 [==============================] - 0s 348us/sample - loss: 0.0219
Epoch 4067/5000
[0.00071605 0.000707531231 0.311516762 0.687059641]
18/18 [==============================] - 0s 353us/sample - loss: 0.0219
Epoch 4068/5000
[0.000715518952 0.000707011553 0.311519116 0.687058389]
18/18 [==============================] - 0s 1ms/sample - loss: 0.0219
Epo

18/18 [==============================] - 0s 347us/sample - loss: 0.0219
Epoch 4120/5000
[0.000688688655 0.000680731318 0.311632723 0.68699789]
18/18 [==============================] - 0s 354us/sample - loss: 0.0219
Epoch 4121/5000
[0.000688188651 0.000680240744 0.311635017 0.686996579]
18/18 [==============================] - 0s 362us/sample - loss: 0.0219
Epoch 4122/5000
[0.00068768661 0.000679749 0.311637104 0.686995447]
18/18 [==============================] - 0s 1ms/sample - loss: 0.0219
Epoch 4123/5000
[0.000687185791 0.000679259188 0.311639369 0.686994195]
18/18 [==============================] - 0s 379us/sample - loss: 0.0219
Epoch 4124/5000
[0.000686684856 0.000678768207 0.311641395 0.686993122]
18/18 [==============================] - 0s 369us/sample - loss: 0.0219
Epoch 4125/5000
[0.000686186075 0.000678279728 0.31164366 0.68699187]
18/18 [==============================] - 0s 356us/sample - loss: 0.0219
Epoch 4126/5000
[0.000685686653 0.000677789969 0.311645657 0.686990857]
1

Epoch 4177/5000
[0.00066089473 0.000653499446 0.311750352 0.686935186]
18/18 [==============================] - 0s 350us/sample - loss: 0.0219
Epoch 4178/5000
[0.000660420512 0.000653034251 0.311752111 0.686934412]
18/18 [==============================] - 0s 351us/sample - loss: 0.0219
Epoch 4179/5000
[0.000659947749 0.00065257086 0.311754286 0.68693316]
18/18 [==============================] - 0s 389us/sample - loss: 0.0219
Epoch 4180/5000
[0.000659476034 0.000652108458 0.311756372 0.686932]
18/18 [==============================] - 0s 361us/sample - loss: 0.0219
Epoch 4181/5000
[0.000659004552 0.000651645649 0.31175825 0.686931074]
18/18 [==============================] - 0s 360us/sample - loss: 0.0219
Epoch 4182/5000
[0.000658533711 0.000651184062 0.311760187 0.68693012]
18/18 [==============================] - 0s 346us/sample - loss: 0.0219
Epoch 4183/5000
[0.000658060657 0.000650721311 0.311762065 0.686929166]
18/18 [==============================] - 0s 366us/sample - loss: 0.0219


18/18 [==============================] - 0s 367us/sample - loss: 0.0219
Epoch 4235/5000
[0.00063421228 0.000627347035 0.311862707 0.686875761]
18/18 [==============================] - 0s 349us/sample - loss: 0.0219
Epoch 4236/5000
[0.000633766409 0.000626909896 0.311864525 0.686874807]
18/18 [==============================] - 0s 362us/sample - loss: 0.0219
Epoch 4237/5000
[0.000633319607 0.000626471534 0.311866373 0.686873853]
18/18 [==============================] - 0s 2ms/sample - loss: 0.0219
Epoch 4238/5000
[0.000632874318 0.000626035209 0.31186831 0.68687284]
18/18 [==============================] - 0s 365us/sample - loss: 0.0219
Epoch 4239/5000
[0.000632429 0.000625597953 0.311870277 0.686871767]
18/18 [==============================] - 0s 348us/sample - loss: 0.0219
Epoch 4240/5000
[0.00063198409 0.000625161512 0.311871946 0.686870873]
18/18 [==============================] - 0s 357us/sample - loss: 0.0219
Epoch 4241/5000
[0.000631539908 0.000624726 0.311874032 0.68686974]
18/18

Epoch 4292/5000
[0.00060944329 0.000603060413 0.311966747 0.686820745]
18/18 [==============================] - 0s 377us/sample - loss: 0.0219
Epoch 4293/5000
[0.00060902047 0.000602646556 0.311968476 0.686819911]
18/18 [==============================] - 0s 326us/sample - loss: 0.0219
Epoch 4294/5000
[0.000608597824 0.000602232409 0.311970145 0.686819]
18/18 [==============================] - 0s 338us/sample - loss: 0.0219
Epoch 4295/5000
[0.000608176866 0.000601819309 0.311972052 0.686818]
18/18 [==============================] - 0s 340us/sample - loss: 0.0219
Epoch 4296/5000
[0.00060775649 0.000601406733 0.311973453 0.686817348]
18/18 [==============================] - 0s 363us/sample - loss: 0.0219
Epoch 4297/5000
[0.000607335707 0.000600994041 0.311975449 0.686816156]
18/18 [==============================] - 0s 376us/sample - loss: 0.0219
Epoch 4298/5000
[0.000606914167 0.00060058129 0.311977267 0.686815202]
18/18 [==============================] - 0s 353us/sample - loss: 0.0219
Ep

Epoch 4350/5000
[0.000585601432 0.000579677697 0.312066376 0.686768353]
18/18 [==============================] - 0s 327us/sample - loss: 0.0219
Epoch 4351/5000
[0.000585202361 0.000579286 0.312068343 0.686767161]
18/18 [==============================] - 0s 564us/sample - loss: 0.0219
Epoch 4352/5000
[0.000584802416 0.000578894222 0.312069714 0.686766565]
18/18 [==============================] - 0s 369us/sample - loss: 0.0219
Epoch 4353/5000
[0.000584403751 0.000578503124 0.312071264 0.68676585]
18/18 [==============================] - 0s 360us/sample - loss: 0.0219
Epoch 4354/5000
[0.000584005727 0.000578112493 0.312072933 0.686764956]
18/18 [==============================] - 0s 343us/sample - loss: 0.0219
Epoch 4355/5000
[0.00058360718 0.000577720755 0.312074572 0.686764121]
18/18 [==============================] - 0s 1ms/sample - loss: 0.0219
Epoch 4356/5000
[0.000583209854 0.000577331288 0.31207639 0.686763048]
18/18 [==============================] - 0s 361us/sample - loss: 0.0219


18/18 [==============================] - 0s 341us/sample - loss: 0.0219
Epoch 4408/5000
[0.000563033682 0.000557535503 0.31216082 0.686718643]
18/18 [==============================] - 0s 1ms/sample - loss: 0.0219
Epoch 4409/5000
[0.000562655739 0.000557164953 0.31216234 0.686717868]
18/18 [==============================] - 0s 345us/sample - loss: 0.0219
Epoch 4410/5000
[0.000562277855 0.000556793937 0.312164068 0.686716914]
18/18 [==============================] - 0s 343us/sample - loss: 0.0219
Epoch 4411/5000
[0.000561899273 0.000556422223 0.312165529 0.68671608]
18/18 [==============================] - 0s 347us/sample - loss: 0.0219
Epoch 4412/5000
[0.000561522495 0.000556053128 0.312167227 0.686715186]
18/18 [==============================] - 0s 342us/sample - loss: 0.0219
Epoch 4413/5000
[0.000561145425 0.000555683102 0.312168896 0.686714292]
18/18 [==============================] - 0s 342us/sample - loss: 0.0219
Epoch 4414/5000
[0.000560768356 0.000555313192 0.312170208 0.68671375

Epoch 4465/5000
[0.000542007503 0.000536897918 0.312248528 0.686672509]
18/18 [==============================] - 0s 369us/sample - loss: 0.0219
Epoch 4466/5000
[0.000541648 0.000536545704 0.312250048 0.686671734]
18/18 [==============================] - 0s 371us/sample - loss: 0.0219
Epoch 4467/5000
[0.000541289919 0.000536193489 0.312251449 0.686671078]
18/18 [==============================] - 0s 330us/sample - loss: 0.0219
Epoch 4468/5000
[0.000540930429 0.000535841507 0.312252909 0.686670363]
18/18 [==============================] - 0s 386us/sample - loss: 0.0219
Epoch 4469/5000
[0.00054057216 0.000535490166 0.312254488 0.686669528]
18/18 [==============================] - 0s 409us/sample - loss: 0.0219
Epoch 4470/5000
[0.000540213543 0.000535137951 0.312255979 0.686668634]
18/18 [==============================] - 0s 408us/sample - loss: 0.0219
Epoch 4471/5000
[0.000539855857 0.000534786901 0.312257409 0.686668]
18/18 [==============================] - 0s 364us/sample - loss: 0.0219

18/18 [==============================] - 0s 372us/sample - loss: 0.0219
Epoch 4523/5000
[0.000521697453 0.000516957254 0.312332869 0.686628461]
18/18 [==============================] - 0s 357us/sample - loss: 0.0219
Epoch 4524/5000
[0.00052135624 0.000516622618 0.31233421 0.686627805]
18/18 [==============================] - 0s 340us/sample - loss: 0.0219
Epoch 4525/5000
[0.000521015725 0.000516288157 0.31233561 0.68662709]
18/18 [==============================] - 0s 342us/sample - loss: 0.0219
Epoch 4526/5000
[0.000520675094 0.000515953812 0.312337101 0.686626256]
18/18 [==============================] - 0s 1ms/sample - loss: 0.0219
Epoch 4527/5000
[0.00052033487 0.000515619875 0.31233868 0.686625361]
18/18 [==============================] - 0s 348us/sample - loss: 0.0219
Epoch 4528/5000
[0.00051999517 0.000515285414 0.312339872 0.686624825]
18/18 [==============================] - 0s 343us/sample - loss: 0.0219
Epoch 4529/5000
[0.000519656111 0.000514952873 0.312341511 0.686623871]
1

Epoch 4580/5000
[0.000502731244 0.00049832993 0.312411398 0.686587572]
18/18 [==============================] - 0s 355us/sample - loss: 0.0219
Epoch 4581/5000
[0.000502406969 0.000498011592 0.312412798 0.686586857]
18/18 [==============================] - 0s 345us/sample - loss: 0.0219
Epoch 4582/5000
[0.000502082461 0.000497692556 0.312414289 0.686585903]
18/18 [==============================] - 0s 357us/sample - loss: 0.0219
Epoch 4583/5000
[0.000501758826 0.000497374102 0.312415361 0.686585486]
18/18 [==============================] - 0s 362us/sample - loss: 0.0219
Epoch 4584/5000
[0.000501435599 0.000497056812 0.312416852 0.686584711]
18/18 [==============================] - 0s 348us/sample - loss: 0.0219
Epoch 4585/5000
[0.000501112547 0.00049673958 0.312418342 0.686583817]
18/18 [==============================] - 0s 350us/sample - loss: 0.0219
Epoch 4586/5000
[0.00050078932 0.000496421824 0.312419593 0.686583161]
18/18 [==============================] - 0s 359us/sample - loss: 0.

18/18 [==============================] - 0s 378us/sample - loss: 0.0219
Epoch 4638/5000
[0.000484373712 0.000480293209 0.312487632 0.686547697]
18/18 [==============================] - 0s 333us/sample - loss: 0.0219
Epoch 4639/5000
[0.000484064745 0.000479990238 0.312489 0.686546922]
18/18 [==============================] - 0s 359us/sample - loss: 0.0219
Epoch 4640/5000
[0.000483757525 0.000479687646 0.312490374 0.686546147]
18/18 [==============================] - 0s 1ms/sample - loss: 0.0219
Epoch 4641/5000
[0.000483449316 0.000479384616 0.312491417 0.68654567]
18/18 [==============================] - 0s 348us/sample - loss: 0.0219
Epoch 4642/5000
[0.000483142037 0.000479082839 0.312492847 0.686544895]
18/18 [==============================] - 0s 343us/sample - loss: 0.0219
Epoch 4643/5000
[0.00048283441 0.000478780101 0.312494099 0.686544359]
18/18 [==============================] - 0s 371us/sample - loss: 0.0219
Epoch 4644/5000
[0.000482526637 0.000478477858 0.31249547 0.686543584]


Epoch 4695/5000
[0.000467197649 0.00046341159 0.3125588 0.686510563]
18/18 [==============================] - 0s 356us/sample - loss: 0.0219
Epoch 4696/5000
[0.000466902973 0.000463122444 0.312559843 0.686510205]
18/18 [==============================] - 0s 354us/sample - loss: 0.0219
Epoch 4697/5000
[0.000466609083 0.000462832832 0.312560856 0.686509669]
18/18 [==============================] - 0s 344us/sample - loss: 0.0219
Epoch 4698/5000
[0.000466315687 0.000462544733 0.312562108 0.686509]
18/18 [==============================] - 0s 348us/sample - loss: 0.0219
Epoch 4699/5000
[0.000466022058 0.000462255877 0.31256339 0.686508358]
18/18 [==============================] - 0s 345us/sample - loss: 0.0219
Epoch 4700/5000
[0.000465729 0.000461968099 0.312564582 0.686507702]
18/18 [==============================] - 0s 334us/sample - loss: 0.0219
Epoch 4701/5000
[0.00046543646 0.000461680116 0.312565804 0.686507106]
18/18 [==============================] - 0s 340us/sample - loss: 0.0219
Epo

18/18 [==============================] - 0s 348us/sample - loss: 0.0219
Epoch 4753/5000
[0.000450538791 0.000447032886 0.312627554 0.686474919]
18/18 [==============================] - 0s 353us/sample - loss: 0.0219
Epoch 4754/5000
[0.000450258551 0.000446757185 0.312628597 0.686474323]
18/18 [==============================] - 0s 344us/sample - loss: 0.0219
Epoch 4755/5000
[0.000449978048 0.000446481834 0.31262958 0.686474]
18/18 [==============================] - 0s 348us/sample - loss: 0.0219
Epoch 4756/5000
[0.000449699059 0.000446207385 0.312630862 0.686473191]
18/18 [==============================] - 0s 348us/sample - loss: 0.0219
Epoch 4757/5000
[0.000449419051 0.000445931626 0.312631935 0.686472774]
18/18 [==============================] - 0s 1ms/sample - loss: 0.0219
Epoch 4758/5000
[0.000449139916 0.000445657 0.312633127 0.686472118]
18/18 [==============================] - 0s 349us/sample - loss: 0.0219
Epoch 4759/5000
[0.000448860606 0.000445382408 0.312634438 0.686471283]
1

Epoch 4810/5000
[0.000434922636 0.000431674096 0.312691927 0.686441481]
18/18 [==============================] - 0s 336us/sample - loss: 0.0219
Epoch 4811/5000
[0.000434655347 0.000431411085 0.312692791 0.686441123]
18/18 [==============================] - 0s 354us/sample - loss: 0.0219
Epoch 4812/5000
[0.000434387708 0.000431147258 0.312693924 0.686440527]
18/18 [==============================] - 0s 364us/sample - loss: 0.0219
Epoch 4813/5000
[0.000434120419 0.000430884422 0.312695086 0.686439931]
18/18 [==============================] - 0s 353us/sample - loss: 0.0219
Epoch 4814/5000
[0.000433853711 0.000430621934 0.312696278 0.686439276]
18/18 [==============================] - 0s 347us/sample - loss: 0.0219
Epoch 4815/5000
[0.000433586974 0.000430359243 0.312697291 0.686438739]
18/18 [==============================] - 0s 354us/sample - loss: 0.0219
Epoch 4816/5000
[0.000433321169 0.000430097687 0.312698483 0.686438084]
18/18 [==============================] - 0s 369us/sample - loss:

18/18 [==============================] - 0s 346us/sample - loss: 0.0219
Epoch 4868/5000
[0.000419752207 0.000416747498 0.312754244 0.686409235]
18/18 [==============================] - 0s 362us/sample - loss: 0.0219
Epoch 4869/5000
[0.000419496762 0.000416495663 0.312755346 0.686408699]
18/18 [==============================] - 0s 406us/sample - loss: 0.0219
Epoch 4870/5000
[0.000419240678 0.000416243798 0.3127563 0.686408162]
18/18 [==============================] - 0s 358us/sample - loss: 0.0219
Epoch 4871/5000
[0.000418986456 0.000415993214 0.312757492 0.686407506]
18/18 [==============================] - 0s 344us/sample - loss: 0.0219
Epoch 4872/5000
[0.000418732379 0.000415743329 0.312758744 0.686406851]
18/18 [==============================] - 0s 357us/sample - loss: 0.0219
Epoch 4873/5000
[0.000418477081 0.000415492395 0.312759846 0.686406136]
18/18 [==============================] - 0s 372us/sample - loss: 0.0219
Epoch 4874/5000
[0.000418222393 0.000415241724 0.312760949 0.68640

Epoch 4925/5000
[0.000405506697 0.000402726262 0.312812835 0.686378896]
18/18 [==============================] - 0s 367us/sample - loss: 0.0219
Epoch 4926/5000
[0.000405262312 0.000402485661 0.312814116 0.686378121]
18/18 [==============================] - 0s 338us/sample - loss: 0.0219
Epoch 4927/5000
[0.000405018451 0.000402245612 0.312814921 0.686377764]
18/18 [==============================] - 0s 360us/sample - loss: 0.0219
Epoch 4928/5000
[0.000404774182 0.000402005127 0.312816232 0.686377]
18/18 [==============================] - 0s 362us/sample - loss: 0.0219
Epoch 4929/5000
[0.000404529972 0.000401764497 0.312816888 0.68637681]
18/18 [==============================] - 0s 1ms/sample - loss: 0.0219
Epoch 4930/5000
[0.000404286955 0.000401525205 0.312817812 0.686376393]
18/18 [==============================] - 0s 351us/sample - loss: 0.0219
Epoch 4931/5000
[0.000404044113 0.000401286146 0.312818915 0.686375737]
18/18 [==============================] - 0s 335us/sample - loss: 0.021

18/18 [==============================] - 0s 333us/sample - loss: 0.0219
Epoch 4983/5000
[0.00039164428 0.000389077846 0.312869906 0.686349452]
18/18 [==============================] - 0s 336us/sample - loss: 0.0219
Epoch 4984/5000
[0.000391411158 0.000388847518 0.31287089 0.686348855]
18/18 [==============================] - 0s 1ms/sample - loss: 0.0219
Epoch 4985/5000
[0.000391177891 0.000388618151 0.312871814 0.686348438]
18/18 [==============================] - 0s 334us/sample - loss: 0.0219
Epoch 4986/5000
[0.000390944 0.000388387678 0.312872648 0.686348081]
18/18 [==============================] - 0s 332us/sample - loss: 0.0219
Epoch 4987/5000
[0.000390711211 0.000388158282 0.312873781 0.686347365]
18/18 [==============================] - 0s 326us/sample - loss: 0.0219
Epoch 4988/5000
[0.000390478439 0.000387929234 0.312874764 0.686346769]
18/18 [==============================] - 0s 334us/sample - loss: 0.0219
Epoch 4989/5000
[0.00039024523 0.000387699576 0.312875628 0.686346471]


In [66]:
curr_total_features = tf.Variable(test_houses, dtype=tf.float32)
labels = test_labels
model.compile(optimizer='adam',
              loss=test_loss(curr_total_features, labels))
test_loss = model.evaluate(gate_testing,  test_labels, verbose=2)

print('\nTest loss:', test_loss)

[0.000387466687 0.000384963059 0.312887 0.68634057]
5/5 - 1s - loss: 0.0106

Test loss: 0.010595306754112244


In [27]:
from sklearn.metrics import mean_squared_error 

fill = [0.288971543, 0.197461739, 0.327833086, 0.185733706]
total = 0
for x in range(18) :
    new_arima = [y * fill[0] for y in curr_total_features[x][0]]
    new_holt = [y * fill[1] for y in curr_total_features[x][1]]
    new_tesla = [y * fill[2] for y in curr_total_features[x][2]]
    new_lstm = [y * fill[3] for y in curr_total_features[x][3]]
    
    tot = [a + b for a, b in zip(new_arima, new_holt)]
    tot = [a + b for a, b in zip(tot, new_tesla)]
    tot = [a + b for a, b in zip(tot, new_lstm)]

    total = total + mean_squared_error(tot, train_labels[x][0]) 
    
total / 18
    

0.08385618222046992

In [18]:
from sklearn.metrics import mean_squared_error 

fill = [0.474082142, 0.00997799449, 0.507308125, 0.00863178261]

new_curr_total_features = tf.Variable(curr_total_features, dtype=tf.float32)

total = 0
for x in range(18) :

    new_arima = new_curr_total_features[x][0] * tf.Variable(fill[0])
    new_holt = new_curr_total_features[x][1] * tf.Variable(fill[1])
    new_tesla = new_curr_total_features[x][2] * tf.Variable(fill[2])
    new_lstm = new_curr_total_features[x][3] * tf.Variable(fill[3])
    
    new = tf.math.add(new_arima, new_holt)
    new = tf.math.add(new, new_tesla)
    new = tf.math.add(new, new_lstm)
    
    total = total + K.mean(K.square(new - train_labels[x][0]))
    
total / 18
    

<tf.Tensor: shape=(), dtype=float32, numpy=0.084915966>

In [82]:
def nn_batch_generalized(x,y,w,lr,n_epoch):
    cost_list = []  # initialize list to store epochs and cost
    #y_hat = np.dot(x,w)  # calculate y_hat for first iteration
    total = np.array([0] * x.shape[2])
    
    for house in range(x.shape[0]) :
        for alg in range(x.shape[1]) :
            total = total + (x[alg] * w[i])
            print(total)
    for epoch in range(n_epoch):  
        dcostdw = 2*0.5*np.dot(-x.T,(y-y_hat))   # notice change from previous function "nn_batch". 
                                                #  Matrix multiplication dcostdw (3x1) = tranpose(X) (3x4)  * (y - y_hat) (4x1) 
                                                # above matrix shapes correspond to below example. for other example shapes may change but this function will work withput any changes needed.
        w = w - lr*dcostdw  # w new (3x1) = w (3x1) - dcostdw (3x1)
        y_hat = np.dot(x,w) # calculate new y_hat using new weights after above steps
        cost = 0.5*np.sum((y - y_hat)**2)  # calculate new cost
        cost_list.append([epoch,cost])
        if epoch%1000==0:
            print("epoch :{:d} cost:{:f}".format(epoch,cost))
        if cost <= 0.001:
            print("epoch :{:d} cost:{:f}".format(epoch,cost))
            break

    cost_list = pd.DataFrame(cost_list,columns=['epoch','cost'])
    return w,cost_list
  
# x = np.array([[3,8,10],
#              [10,7,2],
#              [2,9,15],
#              [1,12,34],
#              [3,1,9]])
x = train_houses
# y = [[51],[60],[57],[85],[22]]
y = train_labels
w = np.ones((x.shape[1],1))
lr = 0.0001
n_epoch=10000
w,cost_list = nn_batch_generalized(x,y,w,lr,n_epoch)
print("y_hat_final:\n", format(np.dot(x,w)))
print("trained weights :\n", format(w))

ValueError: operands could not be broadcast together with shapes (4,) (4,7027) 